import React, { useRef } from "react";
import styled from "styled-components";
import PropTypes from 'prop-types';
import { Button } from "@material-ui/core";
import { DOMParser } from 'xmldom';


//doc.documentElement.setAttribute('x', 'y')
//doc.documentElement.setAttributeNS('./lite', 'c:x', 'y2')
//alert(doc)
//const nsAttr = doc.documentElement.getAttributeNS('./lite', 'x')
//console.info(nsAttr)

const downloadTxtFile = (item) => {
  const doc = new DOMParser().parseFromString(
    `<?xml version="1.0" encoding="UTF-8"?>
    <Root>
      <App>ECUS5VNACCS2018</App>
      <DBVersion>279</DBVersion>
      <LastUpdate>29/10/2020</LastUpdate>
      <VersionMessage>1.0</VersionMessage>
      <Date>9/1/2021</Date>
      <DToKhaiMDIDs>
        <DToKhaiMD>
          <Data>
            <_DToKhaiMDID>5839</_DToKhaiMDID>
            <_XorN>N</_XorN>
            <SOTK>${item.name}</SOTK>
            <SOTK_DAU_TIEN>${item.number}</SOTK_DAU_TIEN>
            <SOTK_NHANH>NULL</SOTK_NHANH>
            <SOTK_TONG>NULL</SOTK_TONG>
            <SOTK_TN_TX>NULL</SOTK_TN_TX>
            <MA_LH>A11</MA_LH>
            <MA_HQ>03CE</MA_HQ>
            <TEN_HQ>CANGHPKVII</TEN_HQ>
            <NAMDK>2021</NAMDK>
            <NGAY_DK>2021-01-05</NGAY_DK>
            <MA_DV>0108999718</MA_DV>
            <MA_BC_DV>(+84)43</MA_BC_DV>
            <DIA_CHI_DV>Số 3B/281 Phố Phương Mai, Phường Kim Liên, Quận Đống Đa, Hà Nội.</DIA_CHI_DV>
            <SO_DT_DV>0108999718</SO_DT_DV>
            <MA_DVUT>NULL</MA_DVUT>
            <DV_DT>MARKET UNION CO.,LTD.</DV_DT>
            <MA_BC_DT>NULL</MA_BC_DT>
            <MA_PTVT>9999</MA_PTVT>
            <TEN_PTVT>CAPE FLORES 2027W</TEN_PTVT>
            <NGAYKH>NULL</NGAYKH>
            <NGAYDEN>2020-01-04</NGAYDEN>
            <VAN_DON>161220HTJY20115187F</VAN_DON>
            <MA_CK>VNDNH</MA_CK>
            <TEN_CK>DINH VU NAM HAI</TEN_CK>
            <MA_CANGNN>CNNGB</MA_CANGNN>
            <CANGNN>NINGBO</CANGNN>
            <MA_GP>NULL</MA_GP>
            <SO_GP>NULL</SO_GP>
            <NGAY_GP>NULL</NGAY_GP>
            <NGAY_HHGP>NULL</NGAY_HHGP>
            <SO_HD>01</SO_HD>
            <TYGIA_USD>NULL</TYGIA_USD>
            <NGAY_HD>2020-09-15</NGAY_HD>
            <NGAY_HHHD>NULL</NGAY_HHHD>
            <NUOC_XK>CN</NUOC_XK>
            <NUOC_NK>VN</NUOC_NK>
            <MA_GH>FOB</MA_GH>
            <SOHANG>1</SOHANG>
            <MA_PTTT>KC</MA_PTTT>
            <MA_NT>USD</MA_NT>
            <TYGIA_VND>23035</TYGIA_VND>
            <MA_NT_TY_GIA_VND>USD</MA_NT_TY_GIA_VND>
            <LEPHI_HQ>NULL</LEPHI_HQ>
            <BL_LPHQ>NULL</BL_LPHQ>
            <GIAYTO>NULL</GIAYTO>
            <TENCH>NULL</TENCH>
            <NGAY_KB>NULL</NGAY_KB>
            <USER_DK>W3492</USER_DK>
            <DDIEM_KH>NULL</DDIEM_KH>
            <PTHUC_KH>NULL</PTHUC_KH>
            <NGAY_KH>NULL</NGAY_KH>
            <USER_KH1>NULL</USER_KH1>
            <USER_KH2>NULL</USER_KH2>
            <USER_PCKH>NULL</USER_PCKH>
            <MA_PHI_BH>D</MA_PHI_BH>
            <MA_NT_PHI_BH>NULL</MA_NT_PHI_BH>
            <PHI_BH>NULL</PHI_BH>
            <SO_DK_PHI_BH>NULL</SO_DK_PHI_BH>
            <MA_PHI_VC>A</MA_PHI_VC>
            <MA_NT_PHI_VC>VND</MA_NT_PHI_VC>
            <PHI_VC>23074050</PHI_VC>
            <NGAY_TH>NULL</NGAY_TH>
            <USER_TH>NULL</USER_TH>
            <TONGTGKB>10020</TONGTGKB>
            <TONGTGTT>253884750</TONGTGTT>
            <MA_NT_TGTT>NULL</MA_NT_TGTT>
            <QUY_VND>NULL</QUY_VND>
            <TR_LUONG>2280.0000</TR_LUONG>
            <DVT_TR_LUONG>KGM</DVT_TR_LUONG>
            <SO_KIEN>600</SO_KIEN>
            <DVT_KIEN>CT</DVT_KIEN>
            <KY_HIEU_SO_HIEU>NULL</KY_HIEU_SO_HIEU>
            <SO_CONTAINER>1</SO_CONTAINER>
            <SO_CONTAINER40>NULL</SO_CONTAINER40>
            <SO_CONTAINER45>NULL</SO_CONTAINER45>
            <NGUOINHAP>NULL</NGUOINHAP>
            <NGAYNHAP>NULL</NGAYNHAP>
            <PLUONG>Do</PLUONG>
            <PASS_DK>0</PASS_DK>
            <PASS_KH>0</PASS_KH>
            <PASS_TH>0</PASS_TH>
            <PASS_GC>0</PASS_GC>
            <TTTK>T</TTTK>
            <PPT_GTGT>NULL</PPT_GTGT>
            <PPT_GTGTUT>NULL</PPT_GTGTUT>
            <DATRUYEN>NULL</DATRUYEN>
            <MA_DVKT>NULL</MA_DVKT>
            <THANHKHOAN>NULL</THANHKHOAN>
            <NGAY_THN_THX>NULL</NGAY_THN_THX>
            <PPT_GTGTKT>NULL</PPT_GTGTKT>
            <NGAY_GIAOTK>NULL</NGAY_GIAOTK>
            <NGAY_NHANTK>NULL</NGAY_NHANTK>
            <NGAY_LUUTK>NULL</NGAY_LUUTK>
            <NVPSINH>NULL</NVPSINH>
            <KIEMHOANK>1</KIEMHOANK>
            <MA_HDTM>A</MA_HDTM>
            <SO_TN_HDTM>NULL</SO_TN_HDTM>
            <SO_HDTM>20SS1207</SO_HDTM>
            <NGAY_HDTM>2020-12-07</NGAY_HDTM>
            <MA_PL_GIA_HDTM>A</MA_PL_GIA_HDTM>
            <TONGTG_HDTM>10020</TONGTG_HDTM>
            <NGAY_VANDON>NULL</NGAY_VANDON>
            <THUE>1</THUE>
            <HTKT>0</HTKT>
            <TYLE_KT>NULL</TYLE_KT>
            <DENNGAY_KH>NULL</DENNGAY_KH>
            <DAIDIEN_DN>NULL</DAIDIEN_DN>
            <NGUOIQDHTKT>NULL</NGUOIQDHTKT>
            <SO_PLTK>0</SO_PLTK>
            <XUAT_NPL_SP>N</XUAT_NPL_SP>
            <THANH_LY>
            </THANH_LY>
            <_SoTN>NULL</_SoTN>
            <_NgayTN>NULL</_NgayTN>
            <_NamTN>NULL</_NamTN>
            <_MaHQTN>NULL</_MaHQTN>
            <_TrangThai>NULL</_TrangThai>
            <_Ten_DV_L1>CôNG TY TNHH XUấT NHậP KHẩU KIM SINH</_Ten_DV_L1>
            <_Ten_DV_L2>NULL</_Ten_DV_L2>
            <_Ten_DV_L3>NULL</_Ten_DV_L3>
            <_DV_DT_L2>NULL</_DV_DT_L2>
            <_DV_DT_L3>NULL</_DV_DT_L3>
            <_TEN_DVUT>NULL</_TEN_DVUT>
            <_TEN_DVKT>NULL</_TEN_DVKT>
            <_TR_LUONG_Net>NULL</_TR_LUONG_Net>
            <_DToKhaiMDIDTempt>NULL</_DToKhaiMDIDTempt>
            <_CT_HDTM_BC>NULL</_CT_HDTM_BC>
            <_CT_HDTM_BS>NULL</_CT_HDTM_BS>
            <_CT_HDonTM_BC>NULL</_CT_HDonTM_BC>
            <_CT_HDonTM_BS>NULL</_CT_HDonTM_BS>
            <_CT_BK_BC>NULL</_CT_BK_BC>
            <_CT_BK_BS>NULL</_CT_BK_BS>
            <_CT_VD_BC>NULL</_CT_VD_BC>
            <_CT_VD_BS>NULL</_CT_VD_BS>
            <_CT_Them1_Ten>NULL</_CT_Them1_Ten>
            <_CT_Them1_BC>NULL</_CT_Them1_BC>
            <_CT_Them1_BS>NULL</_CT_Them1_BS>
            <_CT_Them2_Ten>NULL</_CT_Them2_Ten>
            <_CT_Them2_BC>NULL</_CT_Them2_BC>
            <_CT_Them2_BS>NULL</_CT_Them2_BS>
            <_CT_Them3_Ten>NULL</_CT_Them3_Ten>
            <_CT_Them3_BC>NULL</_CT_Them3_BC>
            <_CT_Them3_BS>NULL</_CT_Them3_BS>
            <_MA_PHU_Max>NULL</_MA_PHU_Max>
            <_THANH_LY_BackUp>NULL</_THANH_LY_BackUp>
            <IsNhanHS>NULL</IsNhanHS>
            <HeSoNhanTGTT>NULL</HeSoNhanTGTT>
            <isPhanBo>NULL</isPhanBo>
            <MA_NT_THUE>NULL</MA_NT_THUE>
            <TongTienThue>25388475</TongTienThue>
            <TongTienThueKH>NULL</TongTienThueKH>
            <TongTienThueTH>NULL</TongTienThueTH>
            <HeSoCIFDN>NULL</HeSoCIFDN>
            <isUseHeSoCIFDN>NULL</isUseHeSoCIFDN>
            <TTTK_HQ>NULL</TTTK_HQ>
            <SoHDXK>NULL</SoHDXK>
            <NgayDKNhapHang>NULL</NgayDKNhapHang>
            <KDT_WAITING>NULL</KDT_WAITING>
            <KDT_REFERENCES>NULL</KDT_REFERENCES>
            <KDT_LASTINFO>T? khai dã du?c khai báo t?i H?i Quan</KDT_LASTINFO>
            <IsNewInfomation>NULL</IsNewInfomation>
            <DToKhaiMDID_ERP>NULL</DToKhaiMDID_ERP>
            <DVan_DonID>NULL</DVan_DonID>
            <MA_HQ_CK>NULL</MA_HQ_CK>
            <MessageID>8B84E3CC7D2C4AC286C6749468</MessageID>
            <LyDoHuy>NULL</LyDoHuy>
            <TinhTrang_NoCO>NULL</TinhTrang_NoCO>
            <TinhTrang_HUY>NULL</TinhTrang_HUY>
            <PreToKhaiID>NULL</PreToKhaiID>
            <PhienBan_TK>CT</PhienBan_TK>
            <NextToKhaiID>NULL</NextToKhaiID>
            <HuongDanPL>NULL</HuongDanPL>
            <Chuyen_Cua_Khau>NULL</Chuyen_Cua_Khau>
            <Noi_Dung_Chuyen_Cua_Khau>NULL</Noi_Dung_Chuyen_Cua_Khau>
            <LyDoSua>NULL</LyDoSua>
            <TTTK_HUY>NULL</TTTK_HUY>
            <Ma_MID>NULL</Ma_MID>
            <NGAY_HOANTHANH>NULL</NGAY_HOANTHANH>
            <ThueTuyetDoi>NULL</ThueTuyetDoi>
            <IsDaDuyet>NULL</IsDaDuyet>
            <NguoiDuyet>NULL</NguoiDuyet>
            <NgayDuyet>NULL</NgayDuyet>
            <GhiChuDuyet>NULL</GhiChuDuyet>
            <IsExport>NULL</IsExport>
            <IsSign>NULL</IsSign>
            <SignData>NULL</SignData>
            <SoHSTK>NULL</SoHSTK>
            <HDGCID>NULL</HDGCID>
            <SO_HD_CT>NULL</SO_HD_CT>
            <NGAY_HD_CT>NULL</NGAY_HD_CT>
            <NGAY_HHHD_CT>NULL</NGAY_HHHD_CT>
            <DIA_DIEM_GIAO_HANG>NULL</DIA_DIEM_GIAO_HANG>
            <NGAY_GIAO_HANG>NULL</NGAY_GIAO_HANG>
            <MA_NGUOI_CHI_DINH_CT>NULL</MA_NGUOI_CHI_DINH_CT>
            <TEN_NGUOI_CHI_DINH_CT>NULL</TEN_NGUOI_CHI_DINH_CT>
            <IsToKhaiCT>0</IsToKhaiCT>
            <DeXuatKhac>NULL</DeXuatKhac>
            <IsToKhaiNho>NULL</IsToKhaiNho>
            <HUY_MA_LY_DO>NULL</HUY_MA_LY_DO>
            <HUY_MA_LOAI>NULL</HUY_MA_LOAI>
            <HUY_TrangThai>NULL</HUY_TrangThai>
            <HUY_SOTN>NULL</HUY_SOTN>
            <HUY_NAMTN>NULL</HUY_NAMTN>
            <HUY_NgayTN>NULL</HUY_NgayTN>
            <HUY_MessageID>NULL</HUY_MessageID>
            <HUY_IsSign>NULL</HUY_IsSign>
            <HUY_SignData>NULL</HUY_SignData>
            <TUYEN_VAN_CHUYEN>NULL</TUYEN_VAN_CHUYEN>
            <Ten_Nguoi_Nhan_Hang>NULL</Ten_Nguoi_Nhan_Hang>
            <Ma_Nguoi_Nhan_Hang>NULL</Ma_Nguoi_Nhan_Hang>
            <Ten_Nguoi_Giao_Hang>NULL</Ten_Nguoi_Giao_Hang>
            <Ma_Nguoi_Giao_Hang>NULL</Ma_Nguoi_Giao_Hang>
            <IsTQDT>1</IsTQDT>
            <KieuPhanBo>0</KieuPhanBo>
            <Chon>NULL</Chon>
            <ThongTinPhanHoi>NULL</ThongTinPhanHoi>
            <PHI_KHAC>NULL</PHI_KHAC>
            <TEN_PHI_KHAC>NULL</TEN_PHI_KHAC>
            <HuyKB>NULL</HuyKB>
            <NGAY_BAT_DAU>NULL</NGAY_BAT_DAU>
            <NGAY_KET_THUC>NULL</NGAY_KET_THUC>
            <HUY_KDT_REFERENCES>NULL</HUY_KDT_REFERENCES>
            <HUY_KDT_WAITING>NULL</HUY_KDT_WAITING>
            <HUY_KDT_LASTINFO>NULL</HUY_KDT_LASTINFO>
            <isUseHeSoI>NULL</isUseHeSoI>
            <NGAY_THUC_XN>NULL</NGAY_THUC_XN>
            <PLUONG_NOIDUNG>NULL</PLUONG_NOIDUNG>
            <IS_TRINH_KY>NULL</IS_TRINH_KY>
            <HUY_IS_TRINH_KY>NULL</HUY_IS_TRINH_KY>
            <IsKHONG_VAN_DON>NULL</IsKHONG_VAN_DON>
            <IS_AN_HAN_THUE>NULL</IS_AN_HAN_THUE>
            <AN_HAN_THUE_LD>NULL</AN_HAN_THUE_LD>
            <AN_HAN_THUE_SN>NULL</AN_HAN_THUE_SN>
            <IS_DAM_BAO_THUE>NULL</IS_DAM_BAO_THUE>
            <DAM_BAO_THUE_HINH_THUC>NULL</DAM_BAO_THUE_HINH_THUC>
            <DAM_BAO_THUE_TRI_GIA>NULL</DAM_BAO_THUE_TRI_GIA>
            <DAM_BAO_THUE_NGAY_BD>NULL</DAM_BAO_THUE_NGAY_BD>
            <DAM_BAO_THUE_NGAY_KT>NULL</DAM_BAO_THUE_NGAY_KT>
            <DAM_BAO_MA_NG_HANG>NULL</DAM_BAO_MA_NG_HANG>
            <DAM_BAO_NAM_PHAT_HANH>NULL</DAM_BAO_NAM_PHAT_HANH>
            <DAM_BAO_KY_HIEU_CT>NULL</DAM_BAO_KY_HIEU_CT>
            <DAM_BAO_SO_CT>NULL</DAM_BAO_SO_CT>
            <MA_THOI_HAN_NOP_THUE>D</MA_THOI_HAN_NOP_THUE>
            <SO_CONTAINER_KHAC>NULL</SO_CONTAINER_KHAC>
            <NGAY_TAM_NHAP_HH>NULL</NGAY_TAM_NHAP_HH>
            <THONG_TU>2</THONG_TU>
            <MA_NGHIEP_VU>IDC</MA_NGHIEP_VU>
            <GUID1>38B311CF-8018-431D-A3AA-DFDDBF7D39FA</GUID1>
            <NHOMTK>881CEDAB-6F5B-4719-97C0-F32C6ECF7576</NHOMTK>
            <ISTEST>NULL</ISTEST>
            <IsVNACCS>1</IsVNACCS>
            <APP_NAME>ECUSK5NET</APP_NAME>
            <IsVersion2>NULL</IsVersion2>
            <TRANG_THAI_SAMSUNG>NULL</TRANG_THAI_SAMSUNG>
            <THANH_LY_KBT>NULL</THANH_LY_KBT>
            <SECSIONID>NULL</SECSIONID>
            <IsUyQuyen>NULL</IsUyQuyen>
            <DSCH810AWBID>NULL</DSCH810AWBID>
            <IS_DUYET>NULL</IS_DUYET>
            <USER_DUYET>NULL</USER_DUYET>
          </Data>
        </DToKhaiMD>
      </DToKhaiMDIDs>
      <DTOKHAIMD_VNACCSs>
        <DTOKHAIMD_VNACCS>
          <Data>
            <DTOKHAIMD_VNACCSID>5109</DTOKHAIMD_VNACCSID>
            <_DToKhaiMDID>5839</_DToKhaiMDID>
            <CONTAINER_NO>NULL</CONTAINER_NO>
            <CONTAINER_NO2>NULL</CONTAINER_NO2>
            <CONTAINER_NO3>NULL</CONTAINER_NO3>
            <CONTAINER_NO4>NULL</CONTAINER_NO4>
            <CONTAINER_NO5>NULL</CONTAINER_NO5>
            <CONTAINER_NO6>NULL</CONTAINER_NO6>
            <CONTAINER_NO7>NULL</CONTAINER_NO7>
            <CONTAINER_NO8>NULL</CONTAINER_NO8>
            <CONTAINER_NO9>NULL</CONTAINER_NO9>
            <CONTAINER_NO10>NULL</CONTAINER_NO10>
            <CONTAINER_NO11>NULL</CONTAINER_NO11>
            <CONTAINER_NO12>NULL</CONTAINER_NO12>
            <CONTAINER_NO13>NULL</CONTAINER_NO13>
            <CONTAINER_NO14>NULL</CONTAINER_NO14>
            <CONTAINER_NO15>NULL</CONTAINER_NO15>
            <CONTAINER_NO16>NULL</CONTAINER_NO16>
            <CONTAINER_NO17>NULL</CONTAINER_NO17>
            <CONTAINER_NO18>NULL</CONTAINER_NO18>
            <CONTAINER_NO19>NULL</CONTAINER_NO19>
            <CONTAINER_NO20>NULL</CONTAINER_NO20>
            <CONTAINER_NO21>NULL</CONTAINER_NO21>
            <CONTAINER_NO22>NULL</CONTAINER_NO22>
            <CONTAINER_NO23>NULL</CONTAINER_NO23>
            <CONTAINER_NO24>NULL</CONTAINER_NO24>
            <CONTAINER_NO25>NULL</CONTAINER_NO25>
            <CONTAINER_NO26>NULL</CONTAINER_NO26>
            <CONTAINER_NO27>NULL</CONTAINER_NO27>
            <CONTAINER_NO28>NULL</CONTAINER_NO28>
            <CONTAINER_NO29>NULL</CONTAINER_NO29>
            <CONTAINER_NO30>NULL</CONTAINER_NO30>
            <CONTAINER_NO31>NULL</CONTAINER_NO31>
            <CONTAINER_NO32>NULL</CONTAINER_NO32>
            <CONTAINER_NO33>NULL</CONTAINER_NO33>
            <CONTAINER_NO34>NULL</CONTAINER_NO34>
            <CONTAINER_NO35>NULL</CONTAINER_NO35>
            <CONTAINER_NO36>NULL</CONTAINER_NO36>
            <CONTAINER_NO37>NULL</CONTAINER_NO37>
            <CONTAINER_NO38>NULL</CONTAINER_NO38>
            <CONTAINER_NO39>NULL</CONTAINER_NO39>
            <CONTAINER_NO40>NULL</CONTAINER_NO40>
            <CONTAINER_NO41>NULL</CONTAINER_NO41>
            <CONTAINER_NO42>NULL</CONTAINER_NO42>
            <CONTAINER_NO43>NULL</CONTAINER_NO43>
            <CONTAINER_NO44>NULL</CONTAINER_NO44>
            <CONTAINER_NO45>NULL</CONTAINER_NO45>
            <CONTAINER_NO46>NULL</CONTAINER_NO46>
            <CONTAINER_NO47>NULL</CONTAINER_NO47>
            <CONTAINER_NO48>NULL</CONTAINER_NO48>
            <CONTAINER_NO49>NULL</CONTAINER_NO49>
            <CONTAINER_NO50>NULL</CONTAINER_NO50>
            <MA_KHAI_TRGIA>6</MA_KHAI_TRGIA>
            <SO_TN_KHAI_TRGIA>NULL</SO_TN_KHAI_TRGIA>
            <MA_NT_GIA_CO_SO>NULL</MA_NT_GIA_CO_SO>
            <GIA_CO_SO>NULL</GIA_CO_SO>
            <MA_KHOAN_DC>NULL</MA_KHOAN_DC>
            <MA_LOAI_DC>NULL</MA_LOAI_DC>
            <MA_NT_DC>NULL</MA_NT_DC>
            <TRIGIA_DC>NULL</TRIGIA_DC>
            <TONG_HS_PB_DC>NULL</TONG_HS_PB_DC>
            <MA_KHOAN_DC2>NULL</MA_KHOAN_DC2>
            <MA_LOAI_DC2>NULL</MA_LOAI_DC2>
            <MA_NT_DC2>NULL</MA_NT_DC2>
            <TRIGIA_DC2>NULL</TRIGIA_DC2>
            <TONG_HS_PB_DC2>NULL</TONG_HS_PB_DC2>
            <MA_KHOAN_DC3>NULL</MA_KHOAN_DC3>
            <MA_LOAI_DC3>NULL</MA_LOAI_DC3>
            <MA_NT_DC3>NULL</MA_NT_DC3>
            <TRIGIA_DC3>NULL</TRIGIA_DC3>
            <TONG_HS_PB_DC3>NULL</TONG_HS_PB_DC3>
            <MA_KHOAN_DC4>NULL</MA_KHOAN_DC4>
            <MA_LOAI_DC4>NULL</MA_LOAI_DC4>
            <MA_NT_DC4>NULL</MA_NT_DC4>
            <TRIGIA_DC4>NULL</TRIGIA_DC4>
            <TONG_HS_PB_DC4>NULL</TONG_HS_PB_DC4>
            <MA_KHOAN_DC5>NULL</MA_KHOAN_DC5>
            <MA_LOAI_DC5>NULL</MA_LOAI_DC5>
            <MA_NT_DC5>NULL</MA_NT_DC5>
            <TRIGIA_DC5>NULL</TRIGIA_DC5>
            <TONG_HS_PB_DC5>NULL</TONG_HS_PB_DC5>
            <NOI_DUNG_KHAI_TRGIA>16122020#&amp;  PT thanh toán: T/T</NOI_DUNG_KHAI_TRGIA>
            <HS_PB_TRGIA>10020</HS_PB_TRGIA>
            <MA_NGUOI_NOP_THUE>1</MA_NGUOI_NOP_THUE>
            <MA_LY_DO_BP>NULL</MA_LY_DO_BP>
            <MA_KTRA_ND>NULL</MA_KTRA_ND>
            <MA_VB_PQUY>NULL</MA_VB_PQUY>
            <MA_VB_PQUY2>NULL</MA_VB_PQUY2>
            <MA_VB_PQUY3>NULL</MA_VB_PQUY3>
            <MA_VB_PQUY4>NULL</MA_VB_PQUY4>
            <MA_VB_PQUY5>NULL</MA_VB_PQUY5>
            <MA_QLY_CHUNG>NULL</MA_QLY_CHUNG>
            <MA_BO_GIAO_THONG>NULL</MA_BO_GIAO_THONG>
            <MA_BO_CONG_THUONG>NULL</MA_BO_CONG_THUONG>
            <MA_LOAI_DINH_KEM>ETC</MA_LOAI_DINH_KEM>
            <SO_DINH_KEM>721465988040</SO_DINH_KEM>
            <MA_LOAI_DINH_KEM2>NULL</MA_LOAI_DINH_KEM2>
            <SO_DINH_KEM2>NULL</SO_DINH_KEM2>
            <MA_LOAI_DINH_KEM3>NULL</MA_LOAI_DINH_KEM3>
            <SO_DINH_KEM3>NULL</SO_DINH_KEM3>
            <TRUNG_CHUYEN_DIA_DIEM>NULL</TRUNG_CHUYEN_DIA_DIEM>
            <TRUNG_CHUYEN_NGAY_DEN>NULL</TRUNG_CHUYEN_NGAY_DEN>
            <TRUNG_CHUYEN_NGAY_KH>NULL</TRUNG_CHUYEN_NGAY_KH>
            <TRUNG_CHUYEN_DIA_DIEM2>NULL</TRUNG_CHUYEN_DIA_DIEM2>
            <TRUNG_CHUYEN_NGAY_DEN2>NULL</TRUNG_CHUYEN_NGAY_DEN2>
            <TRUNG_CHUYEN_NGAY_KH2>NULL</TRUNG_CHUYEN_NGAY_KH2>
            <TRUNG_CHUYEN_DIA_DIEM3>NULL</TRUNG_CHUYEN_DIA_DIEM3>
            <TRUNG_CHUYEN_NGAY_DEN3>NULL</TRUNG_CHUYEN_NGAY_DEN3>
            <TRUNG_CHUYEN_NGAY_KH3>NULL</TRUNG_CHUYEN_NGAY_KH3>
            <TRUNG_CHUYEN_DIEM_CUOI>NULL</TRUNG_CHUYEN_DIEM_CUOI>
            <TRUNG_CHUYEN_NGAY_KT>NULL</TRUNG_CHUYEN_NGAY_KT>
            <TRUNG_CHUYEN_GHI_CHU>Contract No. 01 (15/09/2020)</TRUNG_CHUYEN_GHI_CHU>
            <MA_DIEM_XEP_HANG_LEN_XE>NULL</MA_DIEM_XEP_HANG_LEN_XE>
            <MA_DIEM_XEP_HANG_LEN_XE2>NULL</MA_DIEM_XEP_HANG_LEN_XE2>
            <MA_DIEM_XEP_HANG_LEN_XE3>NULL</MA_DIEM_XEP_HANG_LEN_XE3>
            <MA_DIEM_XEP_HANG_LEN_XE4>NULL</MA_DIEM_XEP_HANG_LEN_XE4>
            <MA_DIEM_XEP_HANG_LEN_XE5>NULL</MA_DIEM_XEP_HANG_LEN_XE5>
            <TEN_DIEM_XEP_HANG_LEN_XE>NULL</TEN_DIEM_XEP_HANG_LEN_XE>
            <DIA_CHI_DIEM_XEP_HANG_LEN_XE>NULL</DIA_CHI_DIEM_XEP_HANG_LEN_XE>
            <MA_PL_BAO_CAO>NULL</MA_PL_BAO_CAO>
            <MA_PL_KTRA>3C</MA_PL_KTRA>
            <MA_HANG_HOA_DD>9019</MA_HANG_HOA_DD>
            <GIO_DK>103042</GIO_DK>
            <NGAY_DK_SUA>NULL</NGAY_DK_SUA>
            <GIO_DK_SUA>NULL</GIO_DK_SUA>
            <MA_PL_VB_PQUY>NULL</MA_PL_VB_PQUY>
            <SO_KB_VB_PQUY>NULL</SO_KB_VB_PQUY>
            <MA_PL_VB_PQUY2>NULL</MA_PL_VB_PQUY2>
            <SO_KB_VB_PQUY2>NULL</SO_KB_VB_PQUY2>
            <MA_PL_VB_PQUY3>NULL</MA_PL_VB_PQUY3>
            <SO_KB_VB_PQUY3>NULL</SO_KB_VB_PQUY3>
            <MA_PL_VB_PQUY4>NULL</MA_PL_VB_PQUY4>
            <SO_KB_VB_PQUY4>NULL</SO_KB_VB_PQUY4>
            <MA_PL_VB_PQUY5>NULL</MA_PL_VB_PQUY5>
            <SO_KB_VB_PQUY5>NULL</SO_KB_VB_PQUY5>
            <MA_PL_VB_PQUY6>NULL</MA_PL_VB_PQUY6>
            <SO_KB_VB_PQUY6>NULL</SO_KB_VB_PQUY6>
            <MA_PL_VB_PQUY7>NULL</MA_PL_VB_PQUY7>
            <SO_KB_VB_PQUY7>NULL</SO_KB_VB_PQUY7>
            <MA_PL_NHAP_HS_PHAN_BO>NULL</MA_PL_NHAP_HS_PHAN_BO>
            <HET_HAN_TAM_NHAP>NULL</HET_HAN_TAM_NHAP>
            <TEN_DD_LUU_KHO>NAM HAI DINH VU</TEN_DD_LUU_KHO>
            <MA_PL_CTHUC_TRGIA>NULL</MA_PL_CTHUC_TRGIA>
            <MA_PL_DC_GIA>NULL</MA_PL_DC_GIA>
            <PP_DC_GIA_KHAI_TRGIA>NULL</PP_DC_GIA_KHAI_TRGIA>
            <MA_PL_NOP_THUE>A</MA_PL_NOP_THUE>
            <SO_TRANG_TK>3</SO_TRANG_TK>
            <MA_QLY_USER>00001</MA_QLY_USER>
            <MA_SAC_THUE>V</MA_SAC_THUE>
            <TEN_SAC_THUE>Thuế GTGT</TEN_SAC_THUE>
            <TONG_THUE>25388475</TONG_THUE>
            <SO_DONG_TONG_THUE>1</SO_DONG_TONG_THUE>
            <MA_SAC_THUE2>NULL</MA_SAC_THUE2>
            <TEN_SAC_THUE2>NULL</TEN_SAC_THUE2>
            <TONG_THUE2>NULL</TONG_THUE2>
            <SO_DONG_TONG_THUE2>NULL</SO_DONG_TONG_THUE2>
            <MA_SAC_THUE3>NULL</MA_SAC_THUE3>
            <TEN_SAC_THUE3>NULL</TEN_SAC_THUE3>
            <TONG_THUE3>NULL</TONG_THUE3>
            <SO_DONG_TONG_THUE3>NULL</SO_DONG_TONG_THUE3>
            <MA_SAC_THUE4>NULL</MA_SAC_THUE4>
            <TEN_SAC_THUE4>NULL</TEN_SAC_THUE4>
            <TONG_THUE4>NULL</TONG_THUE4>
            <SO_DONG_TONG_THUE4>NULL</SO_DONG_TONG_THUE4>
            <MA_SAC_THUE5>NULL</MA_SAC_THUE5>
            <TEN_SAC_THUE5>NULL</TEN_SAC_THUE5>
            <TONG_THUE5>NULL</TONG_THUE5>
            <SO_DONG_TONG_THUE5>NULL</SO_DONG_TONG_THUE5>
            <MA_SAC_THUE6>NULL</MA_SAC_THUE6>
            <TEN_SAC_THUE6>NULL</TEN_SAC_THUE6>
            <TONG_THUE6>NULL</TONG_THUE6>
            <SO_DONG_TONG_THUE6>NULL</SO_DONG_TONG_THUE6>
            <LAN_SUA>NULL</LAN_SUA>
            <NGAY_KB_NOP_THUE>NULL</NGAY_KB_NOP_THUE>
            <GIO_KB_NOP_THUE>NULL</GIO_KB_NOP_THUE>
            <TIEU_DE_KB_NOP_THUE>NULL</TIEU_DE_KB_NOP_THUE>
            <AN_HAN_MA_SAC_THUE>NULL</AN_HAN_MA_SAC_THUE>
            <AN_HAN_TEN_SAC_THUE>NULL</AN_HAN_TEN_SAC_THUE>
            <AN_HAN_NGAY_NOP_THUE>NULL</AN_HAN_NGAY_NOP_THUE>
            <AN_HAN_MA_SAC_THUE2>NULL</AN_HAN_MA_SAC_THUE2>
            <AN_HAN_TEN_SAC_THUE2>NULL</AN_HAN_TEN_SAC_THUE2>
            <AN_HAN_NGAY_NOP_THUE2>NULL</AN_HAN_NGAY_NOP_THUE2>
            <AN_HAN_MA_SAC_THUE3>NULL</AN_HAN_MA_SAC_THUE3>
            <AN_HAN_TEN_SAC_THUE3>NULL</AN_HAN_TEN_SAC_THUE3>
            <AN_HAN_NGAY_NOP_THUE3>NULL</AN_HAN_NGAY_NOP_THUE3>
            <AN_HAN_MA_SAC_THUE4>NULL</AN_HAN_MA_SAC_THUE4>
            <AN_HAN_TEN_SAC_THUE4>NULL</AN_HAN_TEN_SAC_THUE4>
            <AN_HAN_NGAY_NOP_THUE4>NULL</AN_HAN_NGAY_NOP_THUE4>
            <AN_HAN_MA_SAC_THUE5>NULL</AN_HAN_MA_SAC_THUE5>
            <AN_HAN_TEN_SAC_THUE5>NULL</AN_HAN_TEN_SAC_THUE5>
            <AN_HAN_NGAY_NOP_THUE5>NULL</AN_HAN_NGAY_NOP_THUE5>
            <AN_HAN_MA_SAC_THUE6>NULL</AN_HAN_MA_SAC_THUE6>
            <AN_HAN_TEN_SAC_THUE6>NULL</AN_HAN_TEN_SAC_THUE6>
            <AN_HAN_NGAY_NOP_THUE6>NULL</AN_HAN_NGAY_NOP_THUE6>
            <AN_HAN_MA_SAC_THUE_VAT>NULL</AN_HAN_MA_SAC_THUE_VAT>
            <AN_HAN_TEN_SAC_THUE_VAT>NULL</AN_HAN_TEN_SAC_THUE_VAT>
            <AN_HAN_NGAY_NOP_THUE_VAT>NULL</AN_HAN_NGAY_NOP_THUE_VAT>
            <AN_HAN_MA_SAC_THUE_VAT2>NULL</AN_HAN_MA_SAC_THUE_VAT2>
            <AN_HAN_TEN_SAC_THUE_VAT2>NULL</AN_HAN_TEN_SAC_THUE_VAT2>
            <AN_HAN_NGAY_NOP_THUE_VAT2>NULL</AN_HAN_NGAY_NOP_THUE_VAT2>
            <AN_HAN_MA_SAC_THUE_VAT3>NULL</AN_HAN_MA_SAC_THUE_VAT3>
            <AN_HAN_TEN_SAC_THUE_VAT3>NULL</AN_HAN_TEN_SAC_THUE_VAT3>
            <AN_HAN_NGAY_NOP_THUE_VAT3>NULL</AN_HAN_NGAY_NOP_THUE_VAT3>
            <AN_HAN_MA_SAC_THUE_VAT4>NULL</AN_HAN_MA_SAC_THUE_VAT4>
            <AN_HAN_TEN_SAC_THUE_VAT4>NULL</AN_HAN_TEN_SAC_THUE_VAT4>
            <AN_HAN_NGAY_NOP_THUE_VAT4>NULL</AN_HAN_NGAY_NOP_THUE_VAT4>
            <AN_HAN_MA_SAC_THUE_VAT5>NULL</AN_HAN_MA_SAC_THUE_VAT5>
            <AN_HAN_TEN_SAC_THUE_VAT5>NULL</AN_HAN_TEN_SAC_THUE_VAT5>
            <AN_HAN_NGAY_NOP_THUE_VAT5>NULL</AN_HAN_NGAY_NOP_THUE_VAT5>
            <AN_HAN_MA_SAC_THUE_VAT6>NULL</AN_HAN_MA_SAC_THUE_VAT6>
            <AN_HAN_TEN_SAC_THUE_VAT6>NULL</AN_HAN_TEN_SAC_THUE_VAT6>
            <AN_HAN_NGAY_NOP_THUE_VAT6>NULL</AN_HAN_NGAY_NOP_THUE_VAT6>
            <TEN_TRUONG_DV_HQ>CCT CC HQ CK cảng HP KV II</TEN_TRUONG_DV_HQ>
            <NGAY_CAP_PHEP>2021-01-07</NGAY_CAP_PHEP>
            <GIO_CAP_PHEP>114126</GIO_CAP_PHEP>
            <NGAY_HOAN_THANH_KT>2021-01-07</NGAY_HOAN_THANH_KT>
            <GIO_HOAN_THANH_KT>114020</GIO_HOAN_THANH_KT>
            <MA_PL_SAU_TQ>NULL</MA_PL_SAU_TQ>
            <NGAY_DUYET_BP>NULL</NGAY_DUYET_BP>
            <GIO_DUYET_BP>NULL</GIO_DUYET_BP>
            <NGAY_HOAN_THANH_KT_BP>NULL</NGAY_HOAN_THANH_KT_BP>
            <GIO_HOAN_THANH_KT_BP>NULL</GIO_HOAN_THANH_KT_BP>
            <SO_NGAY_CHO_CAP_PHEP>NULL</SO_NGAY_CHO_CAP_PHEP>
            <TIEU_DE_THONG_QUAN>NULL</TIEU_DE_THONG_QUAN>
            <NGAY_HUY_KB>NULL</NGAY_HUY_KB>
            <GIO_HUY_KB>NULL</GIO_HUY_KB>
            <NGAY_XLY_TAY>NULL</NGAY_XLY_TAY>
            <GIO_XLY_TAY>NULL</GIO_XLY_TAY>
            <NGAY_DK_DLIEU>2021-01-05</NGAY_DK_DLIEU>
            <GIO_DK_DLIEU>102550</GIO_DK_DLIEU>
          </Data>
        </DTOKHAIMD_VNACCS>
      </DTOKHAIMD_VNACCSs>
      <DTOKHAIMD_VNACCS2s>
        <DTOKHAIMD_VNACCS2>
          <Data>
            <DTOKHAIMD_VNACCS2ID>5086</DTOKHAIMD_VNACCS2ID>
            <_DTOKHAIMDID>5839</_DTOKHAIMDID>
            <MA_PHAN_LOAI_HH>NULL</MA_PHAN_LOAI_HH>
            <CANHAN_TOCHUC>4</CANHAN_TOCHUC>
            <MA_HIEU_PTVC>2</MA_HIEU_PTVC>
            <NHOM_HO_SO>00</NHOM_HO_SO>
            <DIA_CHI_DT1>8F,NO.1 BUILDING</DIA_CHI_DT1>
            <DIA_CHI_DT2>HI-TECH SCIENCE &amp;TECHNOLOGY SQUARE</DIA_CHI_DT2>
            <DIA_CHI_DT3>NO.1498, JIANGNAN ROAD</DIA_CHI_DT3>
            <DIA_CHI_DT4>NINGBO, CHINA</DIA_CHI_DT4>
            <MA_GP2>NULL</MA_GP2>
            <SO_GP2>NULL</SO_GP2>
            <MA_GP3>NULL</MA_GP3>
            <SO_GP3>NULL</SO_GP3>
            <MA_GP4>NULL</MA_GP4>
            <SO_GP4>NULL</SO_GP4>
            <MA_GP5>NULL</MA_GP5>
            <SO_GP5>NULL</SO_GP5>
            <VAN_DON2>NULL</VAN_DON2>
            <VAN_DON3>NULL</VAN_DON3>
            <VAN_DON4>NULL</VAN_DON4>
            <VAN_DON5>NULL</VAN_DON5>
            <MA_DD_LUU_KHO>03CES15</MA_DD_LUU_KHO>
            <TYGIA_VND3>NULL</TYGIA_VND3>
            <MA_NT_TY_GIA_VND3>NULL</MA_NT_TY_GIA_VND3>
            <TYGIA_VND2>NULL</TYGIA_VND2>
            <MA_NT_TY_GIA_VND2>NULL</MA_NT_TY_GIA_VND2>
            <IS_BL_THUE>NULL</IS_BL_THUE>
            <BL_THUE_MA_NG_HANG>NULL</BL_THUE_MA_NG_HANG>
            <BL_THUE_MA_DV>NULL</BL_THUE_MA_DV>
            <BL_THUE_KY_HIEU_CT>NULL</BL_THUE_KY_HIEU_CT>
            <BL_THUE_SO_CT>NULL</BL_THUE_SO_CT>
            <BL_THUE_NAM_CT>NULL</BL_THUE_NAM_CT>
            <BL_THUE_NGAY_BD>NULL</BL_THUE_NGAY_BD>
            <BL_THUE_NGAY_KT>NULL</BL_THUE_NGAY_KT>
            <BL_THUE_NGAY_KY>NULL</BL_THUE_NGAY_KY>
            <BL_THUE_LOAI>NULL</BL_THUE_LOAI>
            <BL_THUE_SO_NGAY>NULL</BL_THUE_SO_NGAY>
            <BL_THUE_TONG_TIEN>NULL</BL_THUE_TONG_TIEN>
            <BL_THUE_TIEN_DU>NULL</BL_THUE_TIEN_DU>
            <BL_MA_NT>NULL</BL_MA_NT>
            <CHI_THI_HQ_MA_LOAI>NULL</CHI_THI_HQ_MA_LOAI>
            <CHI_THI_HQ_NGAY>NULL</CHI_THI_HQ_NGAY>
            <CHI_THI_HQ_TEN>NULL</CHI_THI_HQ_TEN>
            <CHI_THI_HQ_ND>NULL</CHI_THI_HQ_ND>
            <CHI_THI_HQ_NGAY2>NULL</CHI_THI_HQ_NGAY2>
            <CHI_THI_HQ_TEN2>NULL</CHI_THI_HQ_TEN2>
            <CHI_THI_HQ_ND2>NULL</CHI_THI_HQ_ND2>
            <CHI_THI_HQ_NGAY3>NULL</CHI_THI_HQ_NGAY3>
            <CHI_THI_HQ_TEN3>NULL</CHI_THI_HQ_TEN3>
            <CHI_THI_HQ_ND3>NULL</CHI_THI_HQ_ND3>
            <CHI_THI_HQ_NGAY4>NULL</CHI_THI_HQ_NGAY4>
            <CHI_THI_HQ_TEN4>NULL</CHI_THI_HQ_TEN4>
            <CHI_THI_HQ_ND4>NULL</CHI_THI_HQ_ND4>
            <CHI_THI_HQ_NGAY5>NULL</CHI_THI_HQ_NGAY5>
            <CHI_THI_HQ_TEN5>NULL</CHI_THI_HQ_TEN5>
            <CHI_THI_HQ_ND5>NULL</CHI_THI_HQ_ND5>
            <CHI_THI_HQ_NGAY6>NULL</CHI_THI_HQ_NGAY6>
            <CHI_THI_HQ_TEN6>NULL</CHI_THI_HQ_TEN6>
            <CHI_THI_HQ_ND6>NULL</CHI_THI_HQ_ND6>
            <CHI_THI_HQ_NGAY7>NULL</CHI_THI_HQ_NGAY7>
            <CHI_THI_HQ_TEN7>NULL</CHI_THI_HQ_TEN7>
            <CHI_THI_HQ_ND7>NULL</CHI_THI_HQ_ND7>
            <CHI_THI_HQ_NGAY8>NULL</CHI_THI_HQ_NGAY8>
            <CHI_THI_HQ_TEN8>NULL</CHI_THI_HQ_TEN8>
            <CHI_THI_HQ_ND8>NULL</CHI_THI_HQ_ND8>
            <CHI_THI_HQ_NGAY9>NULL</CHI_THI_HQ_NGAY9>
            <CHI_THI_HQ_TEN9>NULL</CHI_THI_HQ_TEN9>
            <CHI_THI_HQ_ND9>NULL</CHI_THI_HQ_ND9>
            <CHI_THI_HQ_NGAY10>NULL</CHI_THI_HQ_NGAY10>
            <CHI_THI_HQ_TEN10>NULL</CHI_THI_HQ_TEN10>
            <CHI_THI_HQ_ND10>NULL</CHI_THI_HQ_ND10>
            <TEST_SOKB>NULL</TEST_SOKB>
            <TEST_KICHBAN>NULL</TEST_KICHBAN>
            <TEST_GHICHU>NULL</TEST_GHICHU>
            <SO_HD_CT_PL>NULL</SO_HD_CT_PL>
            <NGAY_HD_CT_PL>NULL</NGAY_HD_CT_PL>
            <NGAY_HHHD_CT_PL>NULL</NGAY_HHHD_CT_PL>
            <SO_HDGTGT>NULL</SO_HDGTGT>
            <NGAY_HDGTGT>NULL</NGAY_HDGTGT>
            <ISAMA>NULL</ISAMA>
            <IsChuyen_ThanhLy>NULL</IsChuyen_ThanhLy>
            <NGAY_VAN_DON>2020-12-16</NGAY_VAN_DON>
            <NGAY_VAN_DON2>NULL</NGAY_VAN_DON2>
            <NGAY_VAN_DON3>NULL</NGAY_VAN_DON3>
            <NGAY_VAN_DON4>NULL</NGAY_VAN_DON4>
            <NGAY_VAN_DON5>NULL</NGAY_VAN_DON5>
            <SO_HDXK>NULL</SO_HDXK>
            <SO_RECORD>NULL</SO_RECORD>
            <TEN_NCC>NULL</TEN_NCC>
            <SO_CT_TT>NULL</SO_CT_TT>
            <NGAY_CT_TT>NULL</NGAY_CT_TT>
            <TYGIA_TT>NULL</TYGIA_TT>
            <NGAY_TAM_NHAP_HH_GOC>NULL</NGAY_TAM_NHAP_HH_GOC>
            <isTKCopy>NULL</isTKCopy>
            <DTOKHAIMDID_Parent>NULL</DTOKHAIMDID_Parent>
            <MA_SP>NULL</MA_SP>
            <IS_VAN_DON_MAWB>0</IS_VAN_DON_MAWB>
            <VAN_DON_MAWB>
            </VAN_DON_MAWB>
            <VAN_DON_MAWB2>
            </VAN_DON_MAWB2>
            <VAN_DON_MAWB3>
            </VAN_DON_MAWB3>
            <VAN_DON_MAWB4>
            </VAN_DON_MAWB4>
            <VAN_DON_MAWB5>
            </VAN_DON_MAWB5>
            <VAN_DON_NAM>NULL</VAN_DON_NAM>
            <VAN_DON_NAM2>NULL</VAN_DON_NAM2>
            <VAN_DON_NAM3>NULL</VAN_DON_NAM3>
            <VAN_DON_NAM4>NULL</VAN_DON_NAM4>
            <VAN_DON_NAM5>NULL</VAN_DON_NAM5>
            <IS_CV1593>1</IS_CV1593>
            <IS_QD2061>0</IS_QD2061>
          </Data>
        </DTOKHAIMD_VNACCS2>
      </DTOKHAIMD_VNACCS2s>
      <DMSG_OUT_REPs>
        <DMSG_OUT_REP>
          <Data>
            <ID>23699</ID>
            <ServiceCode>IDA</ServiceCode>
            <MsgOutCode>IDA</MsgOutCode>
            <MsgOutName>
            </MsgOutName>
            <MsgDate>2021-01-05</MsgDate>
            <LoaiChungTu>10</LoaiChungTu>
            <ChungTuID>5839</ChungTuID>
            <SoChungTu>NULL</SoChungTu>
            <MsgSubject>
            </MsgSubject>
            <MsgDivision>
            </MsgDivision>
            <MsgTerm>
            </MsgTerm>
            <MsgType>
            </MsgType>
            <MsgInputID>753654780</MsgInputID>
            <MsgIndexTag>
            </MsgIndexTag>
            <MsgDes>
            </MsgDes>
            <MsgBody>DysAAB+LCAAAAAAABADtvQdgHEmWJSYvbcp7f0r1StfgdKEIgGATJNiQQBDswYjN5pLsHWlHIymrKoHKZVZlXWYWQMztnbz33nvvvffee++997o7nU4n99//P1xmZAFs9s5K2smeIYCqyB8/fnwfPyLSND17epzGn+/e23+4t7Ozu7t3b//+pw8OPt1/+PDgZKDx/+uegycH+6f3Tk4ePN072T8+2Tv49OTTB/sP9z89MC0e3L/36f39Bwc7w0C+yWd3w3dE5J29e79x4n/W/8v83//0eHeXPvqNk73fONn/jZOdeyen+HRnx7Xzf9vZ3Tl4+PDhg90D/vPkH/3blhfpm+v0zYtvfzv9vdf/8d/zl7fpi/l//Pf89av096Iff/U6/b2KRfq6WM79Xn9ePr9xsvXJwf6dfZql1//x3/snp/ee3N072E1fzvHHy/k/8Tf9E38x0fKLrBjxX//x3/vn05+g3vPiH/1rlqP0J4i6f/0y/cf+JGpP3/xjf1I2Sr/9j/5F6Yv/+O/9s4vxjd3/f/Xp8Jz9tNMofOlHz6anR7wvjl/9Xqdv0q9enH35Ij35cjx6/ubp+3OUB/Y3Tg6ejV58Od5Nn3x19vzp2YvPo+2/fbb95vTk2+nrk7PTF6R4fiH+evHl8y8//33S1z/x1fGrU2oEMPsPD0bpd86OX3z+4vhF+urL46cdSC+oiydfjtKTb5+9GDBHpK1efFN8onB+42T30929vZ1vv/nO77NHKvj+7sGDZwNtNz8/N40+hZo/eWPf2ds7oA9+r8+/EEPwevf+raD90J7fOCE98FB/PTl+eZo+e/7lq9PX6d7O3oPvxtrv7O/s0pc0qqcvvs2fEDN+O/3Jr9IXx1+k3z4+678knELsZLgq1sRrS4aZDWga/f/QhPzwvzsOvyCLv/P6NRHnQay5bbTzAAwOAv5eJ/oRAXr2JVHnq9dPe33t7nDbTwNdYP7pPQzrJ18EYPbu7TzY37mPGRt403yiVN/cwcCnPw9eFNW0t/PjvzBNX75J23lGTlhb/aN/8fJR+ubum9hLP3p+9Pzo6TyD8mVkM2zofxT+HmrLm1qfvjn5jZMHe7v7n95/eHBAdiyiAoY+Gvrth/DlSbVs62xKUWA1pqg03dq9f3fn4V0oojum1Y8eeQb1eYzaP+zn567nHz23f37EKT96bvf8iFN+9Nzu+RGn/Oi53fMjTvnRc7vnR5zyo+d2z4845f9Lz88lrj/ilB89t3t+xCk/em73/IhTfvTc7qG16J3dh7s7uzvyl/3Yb9L9nf/9jZMn//Hf+6cu0+XFP/qXLNLp/B/9S5bp5T/6F6WLrGmyi1w+GaWLapaX6bMnezs7o3Re/cd/z1/cpv/Yn/wf/71/9vIinfzHf8/fTD/+sT+5+I//3j9ySev2Oz959/7Ot39w9979ne+O0uX8H/1Ll+kcX67T43aeLzP+8C9Km//476Fv3q3/47/nL28fpV8cv/q9Tt+kX704+/JFevLlePT8zVPq+D/+e//cAiu5v7tD/0fP/xceWn55Qdy1012a8n7/dGfnN05enpze9Jk8upwvv386fqCL/rZtXFVJ7/7/Og39d/sgfuPkJ5+QbPnfxhr1fv9/QaP/B32m+2QPKwAA</MsgBody>
            <MsgContent>NULL</MsgContent>
            <TrangThai>E</TrangThai>
            <GUID>cf7062ff-be58-4d89-9e0e-7d2b385ba617</GUID>
            <SendOrRecv>S</SendOrRecv>
            <Terminal_ID>64998C</Terminal_ID>
            <isDaXem>1</isDaXem>
            <UserName>Root</UserName>
            <PCName>SMILEOFDEVIL-PC</PCName>
            <IsCompress>1</IsCompress>
          </Data>
        </DMSG_OUT_REP>
        <DMSG_OUT_REP>
          <Data>
            <ID>23700</ID>
            <ServiceCode>IDC</ServiceCode>
            <MsgOutCode>IDC</MsgOutCode>
            <MsgOutName>
            </MsgOutName>
            <MsgDate>2021-01-05</MsgDate>
            <LoaiChungTu>10</LoaiChungTu>
            <ChungTuID>5839</ChungTuID>
            <SoChungTu>NULL</SoChungTu>
            <MsgSubject>
            </MsgSubject>
            <MsgDivision>
            </MsgDivision>
            <MsgTerm>
            </MsgTerm>
            <MsgType>
            </MsgType>
            <MsgInputID>519594001</MsgInputID>
            <MsgIndexTag>
            </MsgIndexTag>
            <MsgDes>
            </MsgDes>
            <MsgBody>ngEAAB+LCAAAAAAABADtvQdgHEmWJSYvbcp7f0r1StfgdKEIgGATJNiQQBDswYjN5pLsHWlHIymrKoHKZVZlXWYWQMztnbz33nvvvffee++997o7nU4n99//P1xmZAFs9s5K2smeIYCqyB8/fnwfPyLSND17epLGn+/e23+4t7Ozu7t3b//+pw8OPt1/+PBgqPH/656D+3v5wf3J7oMH92a7+cHkfO/h+cF0Z2f/vmlxf/fh/Yf7NMBNYL65Z1M3O4TX7v5vnOzu3Hvw6f69g4f393Z+4+T/AfjYsHueAQAA</MsgBody>
            <MsgContent>NULL</MsgContent>
            <TrangThai>E</TrangThai>
            <GUID>3cf0123c-4232-43bf-8525-70f8e918dd82</GUID>
            <SendOrRecv>S</SendOrRecv>
            <Terminal_ID>64998C</Terminal_ID>
            <isDaXem>1</isDaXem>
            <UserName>Root</UserName>
            <PCName>SMILEOFDEVIL-PC</PCName>
            <IsCompress>1</IsCompress>
          </Data>
        </DMSG_OUT_REP>
        <DMSG_OUT_REP>
          <Data>
            <ID>23702</ID>
            <ServiceCode>
            </ServiceCode>
            <MsgOutCode>VAD3AC0</MsgOutCode>
            <MsgOutName>Bản xác nhận nội dung khai báo nhập khẩu (LUỒNG ĐỎ)</MsgOutName>
            <MsgDate>2021-01-05</MsgDate>
            <LoaiChungTu>10</LoaiChungTu>
            <ChungTuID>5839</ChungTuID>
            <SoChungTu>103764389520</SoChungTu>
            <MsgSubject>103764389520</MsgSubject>
            <MsgDivision>001</MsgDivision>
            <MsgTerm>E</MsgTerm>
            <MsgType>P</MsgType>
            <MsgInputID>519594001</MsgInputID>
            <MsgIndexTag>
            </MsgIndexTag>
            <MsgDes>Q</MsgDes>
            <MsgBody>RD8AAB+LCAAAAAAABADtvQdgHEmWJSYvbcp7f0r1StfgdKEIgGATJNiQQBDswYjN5pLsHWlHIymrKoHKZVZlXWYWQMztnbz33nvvvffee++997o7nU4n99//P1xmZAFs9s5K2smeIYCqyB8/fnwfPyLezIsmpf9ly/T13S/OvjhNm+Jimc/SRd402UX+Gye/cbLNz6ef7t/feXjyZHfv+GDv4TH+eXZv5+DBk0+fPDt9crr/Gycn1bLNl+32m+tV/ih9k79r767KrFgeptN5Vjd5+9lHX715tn3wEYCm6csUz08eP713fLKzt7O3u7O7c393595Omn733v7DvdQ9n+4/fHhw4n3wtR6C/eDT/XsHD+/v7dzYOPK8FDR2du7tf3r/3s7ewx3/25379w52Hzx4GH4aPjs7u6cv6ef93Yf3H+7TX8NNv8HnJzrdBH/u7O4dPDz4jROfODQ7mCD34C/z/+DTe/TP8e4uv7D3GyfEBA93dh8SKxy/+PzbL3+vnzw7+42THYK3c5/6oSnmfnb29xwg81vwCb2wu3Pw8OHDB7sH/MnJP/q3vfg8ffP7pG9efPvb6e/91X/89/zlb9IX3/6P/56//mX6e9GPv/qr9Pc6+yJ9ffbi2z6GPy+f3zjZ+uRg/87+vd84ef0f/71/cnrvyd29g9305Rx/vJz/E3/TP/EXLy/SL7JixH/9x3/vn09//l7FIn1e/KN/zXKU/sSayLpM/7E/idrTN//Yn5SN0m//o39R+uI//nv/7GJ8Y/f/X306PGc/7TQKX/rRs+npEe+L41e/1+mb9KsXZ1++SE++HI+ev3n6/hzlgf2Nk4NnoxdfjnfTJ1+dPX96Rkoi1v7bZ9tvTk++nb4+OTt9cXKa/kL89eLL519+/vukr3/iq+NXp9QIYPYfHozS75yR9npx/CJ99eXx0w6kF9TFky9H6cm3z14cR/riRicvvik+UThfB5x9dffT3b29nW+/+c7vs7ezu3t/9+DBs4G2m5+fm0afwnycvOE/9/YOdsY7+OD3+vwLfED2ZOfeyenr3fs0M8dfpN8+Pkufwgb85FcK4ydfPKU/f+PEfGpaRTs8eUGTa+Y41sRrS4rioXnt+OVp+uz5l69OX6dk5B58N9Z+Z58t4M6txv5De0I73P//MZn1ndevCfMHt4Iif+08AMdhrL/XiX5EgJ59SbT96vXTHgV2dzp02SNX6mD/wf3gQ26F2cenv7HxUOLk/OF/96n3hSI3NNP8+RCcY2bZgBj3dh7s74AWTwfeNJ8YomzsYODTnwcvih7c2/nxX0iu/Ju0nWfLedpW/+hfvKRg5e6b2Es/en70/OjpPKShfuPkzZyihH8w/fzN5z3BYfkzKpz+2DUyO/QEX+KP/5+8EFDB/1aMICn2e/fHbM6C9/t/U2shIlmH9J6Q9PTNyW+cPNjbpVTEw4MD8i66r0Ug8V/I0tTZtE1fVGOK/tOt3ft3dx7ehWa847f80TNsSuCFhGy9kTl+Vp+fu55/9Nz++RGn/Oi53fMjTvnRc7vnR5zyo+d2z4845UfP7Z4fccrPr+frj/ZHnPKj53bPjzjlR8/tnh9xyo+e2z0/4pQfPbd7+pzyszBvv/Gtlwf+f9my+9sP4Uvk3x/u7D7c3dnd6Tb6jZMn//Hf+6cu0+XFP/qXLNLp/B/9S5bp5T/6F6WLrGmyi1w+GaWLapaX6bMnezs7o3Re/cd/z1/cpv/Yn/wf/71/9vIinfzHf8/fTD/+sT+5+I//3j9ymdLC8U/evb/z7R/cvXd/57ujdDn/R//SZTrHl+v0uJ3ny4w//IvS5j/+e+ibd7Q69pe3j9Ivjl/9Xqdv0q9enH35Ij35cjx6/uYpdfwf/71/bpHu7uz87mY8P3r+v/F4IvEpVu5enpyqpPj/izUJH5r7vR39dPfT8QNdEwzbmtVDaRiXxvBT+cv7bH/v3u7+7njvvoFNK4ibua4j971eCZmTF/T/b5+9OMbXT3ghrPMokAhy+lF8MLd9blh+/sknpBj0d/NpSEuvsfy7O0SUPoRvaAQ3fzLwZaThDUzQfQY7/9GYus+PxvT/3TH9xsk2P59+un9/5+HJk92944O9h8f459m9nYMHTz598uz0yek+KbNq2ebLdvvN9Sp/lGarVVlMs7aolnffba/eTpsH201xsczadZ0fpstskX/2UbMoFvl49aD5yHu9zpbNeV5vny6n1axYXjxKJ1mTf+r18LRoVlVTADZ11LbZdL6gzw/T86LM+5B/4+SLs7Ozr45/n+/8XtVPnc0vpy+Of2J6UtFnP/Hm5OTk6c7J8U+cvjv5wfF3nlx8VT+9+OLk84uvjr84bj4/ef2LPn99Nrn3GydPf+L028fZycmTyduri4vv7hLE02V2/PT44vTk+OKLq0/uX109/Qm/h9PnT37i+Oonf/r0+RfHbz8nm7H71emT+RcnP/l2/9233xxPnly8+Mknx9UXz06/M58UT55Orp/c/6nf+6uLn9ibryaLi4vp5/PdL15fXH3n4vd5+pM/8RNk154+eYhW72bffbY++/xFNfvu/eXZt1/Rzy8upnsH4ZtP9n/vp29O73/x9O27Fz99/IMXb37iB0SHZxV9erbDnz6VT+mzq9kbwdLH8fSnj39CcCSCfPXTT6uTJ1/+xsn+ZP1T2ZvTn/ziyRfS+urqi5/45PNPV/e+uni1t5yvf9FP3v/i1durZ1eM9e/19MmTE3rn9zl79ubpxenbi984+Ymdn37601/dP/vi9fHVt3VsT5/MvqJWX715O70gaA9Wp19cvP7y80+rt28vvvrJn3zy5qdPTo5fnzGFf+PEo/ETovHTi4vTl8dPqcVPVCf0+5Pj3+urN+Xd1z9oPn37k692Jt/emxf501fPP53s7u0uf+9ns984mT9tDvavLt7efXL/9/lF+0/v/cSX95ftt5/Ws+88f/n529O95Un+06+e7Ba/6Nu/z97+vf3i6duvlrOXT3YvH97/YvrwJ6vfOPlF350+fXa+un5zcPf8q997/p1m/YPLs69+oj6u8/1v3y+m+fPdk8Xk6jvz03ef3q1/8Pnp+sHB5OqnJ69/77v7r4nGv3Fy/tPr183s/Gq5OmjevXh+0ew/nD57/dVP332+3L2+e/7qp5/l+XfOf9H+5e9198svmvVXxztvjsuH+/fffnH6k/tPf/r3IXP7qn15uv/p/ZOD9jvL5VfVYvL84fWDT37qxfIHb6q3y4P86c53Dq6enPzUye/9+ec/uf9T8+IXNS9n+1/tfPf4J08+/erbNJvz62d3nzx5nd37/Dvz8vPTd8/ufvfNT5/eX1a7u9WXZz/xYv1FVdz7Rcf3qouXx9/+5OV3Tt+9fLb3xcnx1enxcfblCXH1oiF5+M5SuWd2evUTJ18c0/c0U7/P2U+dHf8+k/2foDl5cvwTJCvfvYBUod3Tq584Pb46O/2Nk4Onxyvw2bdff3V69tPHF08uLuonF6fPnvzElN74fc5+r6vfh2b5q28fX/3E5ycFvf0TxJY/Pf3q+OLs6jvMD14/L548ufjus/Inf/BTv/fZxVd75ZIk6/KnSLqyz8t1dvLkKvv2V1ff/gniulc7Xz558vucPjv+9rvfOPlysnv9xcFX94qf/PKTJr/71f1Pf3p2b6/Y+eLs858U3L44vfh9dq4ufp9fdPzs+Kt3P/Fif+ey/vLl1Yt2/e6rL0guXs6f3/t9Dn6fafXdT95O3jypv/iJ5urkJ5i7Pz+9+g6oOvviCY/99OTi6qufWJAMn764PPt2Wc5ePyHp9jB89/LN8QORvS++eMGtnu3+Pt/dv/h99ua7k8X0YkYS/vtcP/kBaYOfzr79k/d/ir77jZOf+vZPrn/qOhjrxe/17DuXk3uvnv7E6wXJx09cfXERzMvpk5Ovvnu2N9+Zffv40984eX798Kd/n9f3l5N7v896tti/nH7erp7fe7L7+xQPf3q6uLr8fe4dr3+fe99pvnh69vnJd08+f338+eefnJ49obkpnxUvSC5m33519WVxcPn77J2uf2rv4d7z5U+tCUKdvX54Nfvu2SXefr734ur54sX15OmTn2bqvjo4/b2fPsm+OFnQKL7z6XE5J1jvB+m4rU7WF7/X7/P7LImS3361M31aXQrm9283os+Ju07AXV89I3f8ijj22QVp7+PC48er49/n9/muhb5HEPC2j98Pjq/QniCYN6rf561748X8+WJ2OSvu702Kh1fZ3tvL6bd/sqDPy+nyJwwuO18c75C9MLaHLM+Tk6uvjo/3ic4/8eTJJ6/v1z9x+tMPL+cX5d2ffpJ98uX9xae/97NXi9lP/uB6/d2LkzfvvvusubwkPfmTx1/e/emH737i7OWX333zyXz2+yxOVj/49surxcPf+9Pv/j4/uNc+3/nOd2bV4uz89N1PPinzdmf3i4PZd39qr3zz6mHzhHA4/s7J57/PV9NPLl49u//tdu+nFwe/93p98XD5+cWX785ffft6/Xs/e/Odi5PJd569mn3708/n2envU/1g99knv/eb3+v+yfya9ORXy/037z7/wXfrxavT07u768tPstW9z5u95z/55AfPyaA9/PwHZ3V9+vanXhdPZzu/98Ns9nt9+vKi+PT8+eXv8+2LtzSbT66r32vvF9376f1FcbD4we/zi9Zf1lf7F1/91Hzxpnx79uX69LsPJ+effvfply9/8J17lzvV8+mXT37i2fHVs5f1J9WE4qpPv7vzZHf3J36vn5p++erzb3/x9unVm6v93+vh5N1Pnu5en//e518erz9f/NSri/anv/vui9/n7OT3/gHZkrKBV3D1e7958l2ym+8pzb4s/15PjxfgB5Hmb+9slGb/zZPjHzx9sHwqXglZf/VLqrNv/z5fPLmwvgnxx3eOf0DexsXbXzR/W3z+8GrnCfHv1bcDf+ftM4ziANb/3RdPT69evDn+wRc/+H3evditrs6ugpanX7wivfidt3d/4t3vvfrkp14/ffHdg+Xn+erhb5x8d3X+7fqL3dkX334b9P/0B89IgqqrkyvVLt/96umT49NfxD4U64lnJekI4qhnP31MmJYX87cXT37qJ744Pf6Js6sTaHnT/9X06mnw9xn5VyfHkImTk19EciF9kg26eEafTj9/8rr5klp927Rw359W/JknRyTdFLo/OSNJOv6p3/t6df9NdvadN59/5+3uVXP5E8ufeNKW+fTTX1R+sjtvq/tfLqqfal4/++Ld7CfPvv3t5veeNj94+tXrBXmDs2z1RfWLXj79zvz3vnr33UX+e/3gO/lPH7z6ibf3n/zen97/RT+4eHpv8unzs3fZyerzcvKLysufvpz93sfTby+n5d0fPLhLlLyudw+aN9/5waefXBXXexcvvnO5+nTdPD9e/T5F+e7L5id33uwX7fo7J0+mqy/Of5/X05/+7vUnbfWdy/J8RXJVkt3cuVr9ot9n+bZ9cf3pu68Onq7fPPvqy2X9YvfNy8kXV8389flPPX3+pNwpq5/6yXX1unmyc/fF5RdXky9fX08vlp98Oyf/4ZNP7v/kT+z/ZPXm3Sdf3mvr86xat3vZ3e/8Ps9+4id/0U+Vrz75yfOr3/vi/OrL7PnFybOdZ+X1T5+cTj49WP3Ui+ynfooc8umnP3iwnOavnjz8RV+9K4vTydPL6tvHz97+1NOzz24fOmxvo+3/AxelPs1EPwAA</MsgBody>
            <MsgContent>NULL</MsgContent>
            <TrangThai>E</TrangThai>
            <GUID>F092805A-8128-4EF2-9016-EA7263BE6159</GUID>
            <SendOrRecv>R</SendOrRecv>
            <Terminal_ID>64998C</Terminal_ID>
            <isDaXem>0</isDaXem>
            <UserName>Root</UserName>
            <PCName>SMILEOFDEVIL-PC</PCName>
            <IsCompress>1</IsCompress>
          </Data>
        </DMSG_OUT_REP>
        <DMSG_OUT_REP>
          <Data>
            <ID>23703</ID>
            <ServiceCode>
            </ServiceCode>
            <MsgOutCode>VAF8030</MsgOutCode>
            <MsgOutName>Chứng từ ghi số lệ phí phải thu</MsgOutName>
            <MsgDate>2021-01-05</MsgDate>
            <LoaiChungTu>10</LoaiChungTu>
            <ChungTuID>5839</ChungTuID>
            <SoChungTu>103764389520</SoChungTu>
            <MsgSubject>103764389520</MsgSubject>
            <MsgDivision>001</MsgDivision>
            <MsgTerm>E</MsgTerm>
            <MsgType>P</MsgType>
            <MsgInputID>519594001</MsgInputID>
            <MsgIndexTag>
            </MsgIndexTag>
            <MsgDes>Q</MsgDes>
            <MsgBody>vhMAAB+LCAAAAAAABADtvQdgHEmWJSYvbcp7f0r1StfgdKEIgGATJNiQQBDswYjN5pLsHWlHIymrKoHKZVZlXWYWQMztnbz33nvvvffee++997o7nU4n99//P1xmZAFs9s5K2smeIYCqyB8/fnwfPyLezIsmpf9ly/T13S/OvjhNm+Jimc/SRd402UX+Gye/cbLNz/3j3Xunnz59+PDg/umnp3sH908+fbZ/f+fk9ODk6f6D3ZPfODmplm2+bLffXK/yR+mb/F17d1VmxfIwnc6zusnbzz766s2z7YOPADRNX6Z4fvL42cHOvZ29nb3dnd2d+7v0e5p+997+w73UPZ/uU7cn3gdf6yHYDz7dv3fw8P7ezo2NI89LQWNn597+p/cJ5Ye7/rc79+8d7N379OD+/aH3qc3O7ulL+nl/9+H9h/v013DTb/D5iU43Ido7uw/uf0qT9x//vX/5NP32f/z3/KVF+ovWxA5vXupfL+f/6N+yvAhB/H/hoTGdpN/+ifTk90qnNBAawrdfpr/XT6ZnZze++v/a5zdOWFB2Pn3w4N69ezTCf/Rve/F5+ub3Sd+8+Pa309/7q//47/nL36QvaN7+ehoq/firv0p/r7Mv0tdnL759I+z/vz+/cUIK5uDhw4cPdg/4z61PDvbv7BMVX//Hf++fnN57cnfvYJe4HX+8nP8Tf9M/8RcTy3yRFSP+6z/+e/98+vP3Khbp8+If/WuWo/Qn1kTlZfqP/UnUnr75x/6kbJR++x/9i9IX//Hf+2cX45uQ+f/s06Gi/dRXrtTm/s4uOPU3To536Z9793d9pfMbJz8xfv6P/jHpybf/0T/kRbeD/48+/pi/rsnMVquymGZtUS3vvttevZ02D7ZhjrN2XeeH6TJb5J991CyKRT5ePWg+8l6vs2Vzntfbp8tpNSuWF4/SSdbkn+67Jk+LZlU1BWBTR22bTecL+vwwPS/KvA/5N06+ODs7++r49/nO71X91Nn8cvri+CemJxV99hNvTk5Onu6cHP/E6buTHxx/58nFV/XTiy9OPr/46viL4+bzk9e/6PPXZxMSq6c/cfrt4+zk5Mnk7dXFxXd3CeLpMjt+enxxenJ88cXVJ/evrp7+hN/D6fMnP3F89ZM/ffr8i+O3n4N5vjp9Mv/i5Cff7r/79pvjyZOLFz/55Lj64tnpd+aT4snTyfWT+z/1e3918RN789VkcXEx/Xy++8Xri6vvXPw+T3/yJ37iKeHw5CFavZt999n67PMX1ey795dn335FP7+4mO4dhG8+2f+9n745vf/F07fvXvz08Q9evPmJHxAdnlX06dkOf/pUPqXPrmZvBEsfx9OfPv4JwZEI8tVPP61Onnz5Gyf7k/VPZW9Of/KLJ19I66urL37ik88/Xd376uLV3nK+/kU/ef+LV2+vnl0x1r/X0ydPTuid3+fs2ZunF6dvL0hcdn766U9/df/si9fHV9/WsT19MvuKWn315u30gqA9WJ1+cfH6y88/rd6+vfjqJ3/yyZufPjk5fn3GFP6NE4/GT4jGTy8uTl8eP6UWP1Gd0O9Pjn+vr96Ud1//oPn07U++2pl8e29e5E9fPf90sru3u/y9n81+42T+tDnYv7p4e/fJ/d/nF+0/vfcTX95ftt9+Ws++8/zl529P95Yn+U+/erJb/KJv/z57+/f2i6dvv1rOXj7ZvXx4/4vpw5+sfuPkF313+vTZ+er6zcHd869+7/l3mvUPLs+++on6uM73v32/mObPd08Wk6vvzE/ffXq3/sHnp+sHB5Orn568/r3v7r8mGv/GyflPr183s/Or5eqgeffi+UWz/3D67PVXP333+XL3+u75q59+luffOf9F+5e/190vv2jWXx3vvDkuH+7ff/vF6U/uP/3p34fU1Kv25Sm5bycH7XeWy6+qxeT5w+sHn/zUi+UP3lRvlwf5053vHFw9Ofmpk9/7889/cv+n5sUval7O9r/a+e7xT558+tW3aTbn18/uPnnyOrv3+Xfm5een757d/e6bnz69v6x2d6svz37ixfqLqrj3i47vVRcvj7/9ycvvnL57+Wzvi5Pjq9Pj4+xLEvrjRUPy8J2lcs/s9OonTr44pu9ppn6fs586O/59Jvs/QXPy5PgnSFa+ewGpQrunVz9xenx1dvobJwdPj1fgs2+//ur07KePL55cXNRPLk6fPfmJKb3x+5z9Xle/D83yV98+vvqJz08KevsniC1/evrV8cXZ1XeYH7x+Xjx5cvHdZ+VP/uCnfu+zi6/2yiVJ1uVPkXRln5fr7OTJVfbtr66+/RPEda92vnzy5Pc5fXb87Xe/cfLlZPf6i4Ov7hU/+eUnTX73q/uf/vTs3l6x88XZ5z8puH1xevH77Fxd/D6/6PjZ8VfvfuLF/s5l/eXLqxft+t1XX5BcvJw/v/f7HPw+0+q7n7ydvHlSf/ETzdXJTzB3f3569R1QdfbFEx776cnF1Vc/sSAZPn1xefbtspy9fkLS7WH47uWb4wcie1988YJbPdv9fb67f/H77M13J4vpxYwk/Pe5fvID0gY/nX37J+//FH33Gyc/9e2fXP/UdTDWi9/r2XcuJ/dePf2J1wuSj5+4+uIimJfTJydfffdsb74z+/YxOc7Prx/+9O/z+v5ycu/3Wc8W+5fTz9vV83tPdn+f4uFPTxdXl7/PveP173PvO80XT88+P/nuyeevjz///JPTsyc0N+Wz4gXJxezbr66+LA4uf5+90/VP7T3ce778qTVBqLPXD69m3z27xNvP915cPV+8uJ48ffLTTN1XB6e/99Mn2RcnCxrFdz49LucE6/0gHbfVyfri9/p9fp8lUfLbr3amT6tLwfz+7Ub0OXHXCbjrq2e/cfLkijj22QVp7+PC48er49/n9/muhb5HEPC2j98Pjq/QniCYN6rf561748X8+WJ2OSvu702Kh1fZ3tvL6bd/sqDPy+nyJwwuO18c75C9MLaHLM+Tk6uvjo/3ic4/8eTJJ6/v1z9x+tMPL+cX5d2ffpJ98uX9xae/97NXi9lP/uB6/d2LkzfvvvusubwkPfmTx1/e/emH737i7OWX333zyXz2+yxOVj/49surxcPf+9Pv/j4/uNc+3/nOd2bV4uz89N1PPinzdmf3i4PZd39qr3zz6mHzhHA4/s7J57/PV9NPLl49u//tdu+nFwe/93p98XD5+cWX785ffft6/Xs/e/Odi5PJd569mn3708/n2envU/1g99knv/eb3+v+yfya9ORXy/037z7/wXfrxavT07u768tPstW9z5u95z/55AfPyaA9/PwHZ3V9+vanXhdPZzu/98Ns9nt9+vKi+PT8+eXv8+2LtzSbT66r32vvF9376f1FcbD4we/zi9Zf1lf7F1/91Hzxpnx79uX69LsPJ+effvfply9/8J17lzvV8+mXT37i2fHVs5f1J9WEXJhPv7vzZHf3J36vn5p++erzb3/x9unVm6v93+vh5N1Pnu5en//e518erz9f/NSri/anv/vui9/n7OT3/gHZkrKBV3D1e7958l2ym+8pzb4s/15PjxfgB5Hmb+9slGb/zZPjHzx9sHwqXglZf/VLqrNv/z5fPLmwvgnxx3eOf0DexsXbXzR/W3z+8GrnCfHv1bcDf+ftM4ziANb/3RdPT69evDn+wRc/mL57UVZXZ1dBy9MvXpFe/L12P38wO56cLD95+1PZdPn67vlP/cbJ4qv8p5bffll98e23Qf9Pf/CMJKi6OrlS7fLdr54+OT79RexDsZ54VpKOII569tPHhGl5MX978eSnfuKL0+OfOLs6gZY3/V9Nr54Gf5+Rf3VyDJk4OflFJBfSJ9mgi2f06fTzJ6+bL6nVt00L9/1pxZ95ckTSfUxzcUaS9OSrvTw//4mnzYq8qDdX75rnJy+X01dP8tf3r66/OP30p37wZg9eysPj33v9nZ+qftHTd6/aslpX316S/3C9M9t7ffKLvnh++vb3OpkdzJ//Xj/9nS+++vabWfX65avfuz65v1o9eX1xL3u4+urTLyY/effJ+f2f/mr11cODu8UXu/kx2c3fp/i9v3pTHOx/fu8nP3/xg9/rpye/z8Xe2+UPPqmvr+tPHk4+b/dX09c/Nb+/evDg82W+k7/Nfvr56eXx8vf64qfK8tsP4cut73313XtPTvLLd/eKB1+s3z39qW8/uPvdnyQP+MFs8uLB7/V7vbv707/XVz/5bvGDg7fLn8reffX2u+XOyeTi7er+7/M8e0lW7+TecjVtXr48bcmV+b2L42KR3fu9i5/49nf2F5/sV6fXy9n5J/Od/evJwf3Zg7Pfp7l6Xp2ftau33/nyuz/4RQXZrB/8osm3s88/bS7fTabnP1jNPj/5fX7Rs+t7pz+9uPjs9qHD9jba/j8Sur3avhMAAA==</MsgBody>
            <MsgContent>NULL</MsgContent>
            <TrangThai>E</TrangThai>
            <GUID>C1DA44BA-D1DA-4EC7-AAA2-9DF1A135EB0B</GUID>
            <SendOrRecv>R</SendOrRecv>
            <Terminal_ID>64998C</Terminal_ID>
            <isDaXem>0</isDaXem>
            <UserName>Root</UserName>
            <PCName>SMILEOFDEVIL-PC</PCName>
            <IsCompress>1</IsCompress>
          </Data>
        </DMSG_OUT_REP>
        <DMSG_OUT_REP>
          <Data>
            <ID>23781</ID>
            <ServiceCode>IID</ServiceCode>
            <MsgOutCode>IID</MsgOutCode>
            <MsgOutName>
            </MsgOutName>
            <MsgDate>2021-01-08</MsgDate>
            <LoaiChungTu>10</LoaiChungTu>
            <ChungTuID>5839</ChungTuID>
            <SoChungTu>NULL</SoChungTu>
            <MsgSubject>
            </MsgSubject>
            <MsgDivision>
            </MsgDivision>
            <MsgTerm>
            </MsgTerm>
            <MsgType>
            </MsgType>
            <MsgInputID>345903394</MsgInputID>
            <MsgIndexTag>
            </MsgIndexTag>
            <MsgDes>
            </MsgDes>
            <MsgBody>ngEAAB+LCAAAAAAABADtvQdgHEmWJSYvbcp7f0r1StfgdKEIgGATJNiQQBDswYjN5pLsHWlHIymrKoHKZVZlXWYWQMztnbz33nvvvffee++997o7nU4n99//P1xmZAFs9s5K2smeIYCqyB8/fnwfPyLSND07e5rGn+/e23+4t7Ozu7t3b//+pw8OPt1/+PDgZKDx/wcfGtXDnXv3Hu7f2PIbeXY3fLezs7O/u/8bJ7s79x58un/v4OH9vZ3fOPl/AFoKwhWeAQAA</MsgBody>
            <MsgContent>NULL</MsgContent>
            <TrangThai>E</TrangThai>
            <GUID>153054c0-7918-418f-8c2f-a752d21eeee4</GUID>
            <SendOrRecv>S</SendOrRecv>
            <Terminal_ID>64998C</Terminal_ID>
            <isDaXem>1</isDaXem>
            <UserName>Root</UserName>
            <PCName>SMILEOFDEVIL-PC</PCName>
            <IsCompress>1</IsCompress>
          </Data>
        </DMSG_OUT_REP>
        <DMSG_OUT_REP>
          <Data>
            <ID>23782</ID>
            <ServiceCode>
            </ServiceCode>
            <MsgOutCode>VAF8010</MsgOutCode>
            <MsgOutName>Thông báo thuế</MsgOutName>
            <MsgDate>2021-01-07</MsgDate>
            <LoaiChungTu>10</LoaiChungTu>
            <ChungTuID>5839</ChungTuID>
            <SoChungTu>103764389520</SoChungTu>
            <MsgSubject>103764389520</MsgSubject>
            <MsgDivision>001</MsgDivision>
            <MsgTerm>E</MsgTerm>
            <MsgType>P</MsgType>
            <MsgInputID>519594001</MsgInputID>
            <MsgIndexTag>
            </MsgIndexTag>
            <MsgDes>Z</MsgDes>
            <MsgBody>ZBsAAB+LCAAAAAAABADtvQdgHEmWJSYvbcp7f0r1StfgdKEIgGATJNiQQBDswYjN5pLsHWlHIymrKoHKZVZlXWYWQMztnbz33nvvvffee++997o7nU4n99//P1xmZAFs9s5K2smeIYCqyB8/fnwfPyLezIsmpf9ly/T13S/OvjhNm+Jimc/SRd402UX+Gye/cbLNz73TnWdPD/ZPD/YP9p/tHzzd393dOd6/d//02c7Os+N793/j5KRatvmy3X5zvcofpW/yd+3dVZkVy8N0Os/qJm8/++irN8+2Dz4C0DR9meL5yeNnBzu7O3s7e7v048Hu7v5Omn733v7DvdQ9n+4/fHhw4n3wtZ7dnXsPPt2/d/Dw/t7OjY0jz0tBY2fn3v6D+/fvH+zu+N/uHHy69/D+w529T+Nvc5ud3dOX9PP+LrXcp7+Gm36Dz091ugn+pNE82N2nyfuP/96/fJp++z/+e/7SIv1Fa2KHNy/1r5fzf/RvWV6EIP6/8NCYTtJv/0R68nulUxoIDeHbL9Pf6yfTs7MbX/1/7fMbJyIouyQfBxC5f/Rve/F5+ub3Sd+8+Pa309/7q//47/nL36QvaN7+ehoq/firv0p/r7Mv0tdnL759I+z/vz+/cUIK5uDhw4cPdg/4z61PDvbv7N/7jZPX//Hf+yen957c3TvYJW7HHy/n/8Tf9E/8xcQyX2TFiP/6j//eP5/+/L2KRfq8+Ef/muUo/Yk1UXmZ/mN/ErWnb/6xPykbpd/+R/+i9MV//Pf+2cX4JmT+P/t0qGg/9ZUrtbm/swtO/Y2T491dKPv/vz3BmOQP/6Oh39//+bC3/9/5vBfx3sxJ0P7B9PM3n7/x3tIvdx/s7Enzvfv3Dg7ILvsv70T+iLXrPX2cokjH/tg8YT8C3PnyQwC//5T/5Iun7nvWS7u+riLv0/eNfuPkJ8bP/9E/Jj359j/6h7zwPv//8vMbJy9Imtbkkf/Hf89fv0iXZKxWaVv8x3/vH7xMW5G0pkov/+O/988t6G8yekVKLf/iJfmE1+k/9if/x3/vH7uc0xf/6F+XrubsHQYQQqjzvEoX//Hf+1dP05ZAFOnbeQU/LL23R9YSL6zJFX0OM9qmzX/89/71GXfwp5PBndCPtFmTWaX3/2z+9k+mL+Wd6X/89/6VmXkPVphAlv/o36/o///X8v7o+fCHpP2BkfavG9hmq1VZTLO2qJZ3322v3k6bB9sImrN2XeeH6TJb5J991CyKRT5ePWg+8l6vs2Vzntfbp8tpNSuWF4/SSdbkn+67Jk+LZlU1BWBTR22bTecL+vwwPS/KvA/5N06+ODs7++r49/nO71X91Nn8cvri+CemJxV99hNvTk5Onu6cHP/E6buTHxx/58nFV/XTiy9OPr/46viL4+bzk9e/6PPXZxNyfp/+xOm3j7OTkyeTt1cXF9/dJYiny+z46fHF6cnxxRdXn9y/unr6E34Pp8+f/MTx1U/+9OnzL47ffg4X76vTJ/MvTn7y7f67b785njy5ePGTT46rL56dfmc+KZ48nVw/uf9Tv/dXFz+xN19NFhcX08/nu1+8vrj6zsXv8/Qnf+InSCU/ffIQrd7Nvvtsffb5i2r23fvLs2+/op9fXEz3DsI3n+z/3k/fnN7/4unbdy9++vgHL978xA+IDs8q+vRshz99Kp/SZ1ezN4Klj+PpTx//hOBIBPnqp59WJ0++/I2T/cn6p7I3pz/5xZMvpPXV1Rc/8cnnn67ufXXxam85X/+in7z/xau3V8+uGOvf6+mTJyf0zu9z9uzN04vTtxdkLXZ++ulPf3X/7IvXx1ff1rE9fTL7ilp99ebt9IKgPVidfnHx+svPP63evr346id/8smbnz45OX59xhT+jROPxk+Ixk8vLk5fHj+lFj9RndDvT45/r6/elHdf/6D59O1PvtqZfHtvXuRPXz3/dLK7t7v8vZ/NfuNk/rQ52L+6eHv3yf3f5xftP733E1/eX7bfflrPvvP85edvT/eWJ/lPv3qyW/yib/8+e/v39ounb79azl4+2b18eP+L6cOfrH7j5Bd9d/r02fnq+s3B3fOvfu/5d5r1Dy7PvvqJ+rjO9799v5jmz3dPFpOr78xP3316t/7B56frBweTq5+evP697+6/Jhr/xsn5T69fN7Pzq+XqoHn34vlFs/9w+uz1Vz999/ly9/ru+auffpbn3zn/RfuXv9fdL79o1l8d77w5Lh/u33/7xelP7j/96d+H3LpX7cvT/U/vnxy031kuv6oWk+cPrx988lMvlj94U71dHuRPd75zcPXk5KdOfu/PP//J/Z+aF7+oeTnb/2rnu8c/efLpV9+m2ZxfP7v75Mnr7N7n35mXn5++e3b3u29++vT+strdrb48+4kX6y+q4t4vOr5XXbw8/vYnL79z+u7ls70vTo6vTo+Psy9PiKsXDcnDd5bKPbPTq584+eKYvqeZ+n3Ofurs+PeZ7P8EzcmT458gWfnuBaQK7Z5e/cTp8dXZ6W+cHDw9XoHPvv36q9Oznz6+eHJxUT+5OH325Cem9Mbvc/Z7Xf0+NMtfffv46ic+Pyno7Z8gtvzp6VfHF2dX32F+8Pp58eTJxXeflT/5g5/6vc8uvtorlyRZlz9F0pV9Xq6zkydX2be/uvr2TxDXvdr58smT3+f02fG33/3GyZeT3esvDr66V/zkl580+d2v7n/607N7e8XOF2ef/6Tg9sXpxe+zc3Xx+/yi42fHX737iRf7O5f1ly+vXrTrd199QXLxcv783u9z8PtMq+9+8nby5kn9xU80Vyc/wdz9+enVd0DV2RdPeOynJxdXX/3EgmT49MXl2bfLcvb6CUm3h+G7l2+OH4jsffHFC271bPf3+e7+xe+zN9+dLKYXM5Lw3+f6yQ9IG/x09u2fvP9T9N1vnPzUt39y/VPXwVgvfq9n37mc3Hv19CdeL0g+fuLqi4tgXk6fnHz13bO9+c7s28ef/sbJ8+uHP/37vL6/nNz7fdazxf7l9PN29fzek93fp3j409PF1eXvc+94/fvc+07zxdOzz0++e/L56+PPP//k9OwJzU35rHhBcjH79qurL4uDy99n73T9U3sP954vf2pNEOrs9cOr2XfPLvH2870XV88XL64nT5/8NFP31cHp7/30SfbFyYJG8Z1Pj8s5wXo/SMdtdbK++L1+n99nSZT89qud6dPqUjC/f7sRfU7cdQLu+urZb5w8uSKOfXZB2vu48Pjx6vj3+X2+a6HvEQS87eP3g+MrtCcI5o3q93nr3ngxf76YXc6K+3uT4uFVtvf2cvrtnyzo83K6/AmDy84XxztkL4ztIcvz5OTqq+PjfaLzTzx58snr+/VPnP70w8v5RXn3p59kn3x5f/Hp7/3s1WL2kz+4Xn/34uTNu+8+ay4vSU/+5PGXd3/64bufOHv55XfffDKf/T6Lk9UPvv3yavHw9/70u7/PD+61z3e+851ZtTg7P333k0/KvN3Z/eJg9t2f2ivfvHrYPCEcjr9z8vnv89X0k4tXz+5/u9376cXB771eXzxcfn7x5bvzV9++Xv/ez9585+Jk8p1nr2bf/vTzeXb6+1Q/2H32ye/95ve6fzK/Jj351XL/zbvPf/DdevHq9PTu7vryk2x17/Nm7/lPPvnBczJoDz//wVldn779qdfF09nO7/0wm/1en768KD49f375+3z74i3N5pPr6vfa+0X3fnp/URwsfvD7/KL1l/XV/sVXPzVfvCnfnn25Pv3uw8n5p999+uXLH3zn3uVO9Xz65ZOfeHZ89exl/Uk1IRfm0+/uPNnd/Ynf66emX776/NtfvH169eZq//d6OHn3k6e71+e/9/mXx+vPFz/16qL96e++++L3OTv5vX9AtqRs4BVc/d5vnnyX7OZ7SrMvy7/X0+MF+EGk+ds7G6XZf/Pk+AdPHyyfildC1l/9kurs27/PF08urG9C/PGd4x+Qt3Hx9hfN3xafP7zaeUL8e/XtwN95+wyjOID1f/fF09OrL+n/X/z023df/mR1dXYVtDz94hXpxadflK/mD168nk9OXnyZP/3Jl/Or3zhZT59Vx29+n3dffPtt0P/THzwjCaquTq5Uu3z3q6dPjk9/EftQrCeelaQjiKOe/fQxYVpezN9ePPmpn/ji9Pgnzq5OoOVN/1fTq6fB32fkX50cQyZOTn4RyYX0STbo4hl9Ov38yevmS2r1bdPCfX9a8WeeHJF0H9NcnJEknf70xc6bCxKJe59++e29J9PP6zft9GpZPrv4RVfF9fqqfvL8J158+6e/e7Va5fVP32+Xb06nRf7w89+rIP9hXf3E2zfF82//3uXpcv5Tv2hvdXbwi37vF6vzvYc/2f4iWvp4Pj35RdmXp5P7n7/+9ur+/OL3Ol2dkpL9idXiu7/o7afffUM2a/3Tk+YHl09/Irv69mL2iz7Nnt67eNhMn/7e937i9/ri8s2958357/3TX35+cfD5Fz/95u7vM3+18yb/zg9eTQ5ePfsBscFPkx91L5seP21mn159fn31i56+e/jt+qJ6Np0W9z9fvPzJn84XT6vpvd+rON+tfu/7O1/89P0XL3/i/hek9t49/6m9/d/nO+vfOLn8QT6Z/+DLd1/9xP0vf9Hv9Yt2yifz1U+Wv891efHJ62X28MnJ25/6vb54+ODTB20+KX7Rg9/7zfonj+d3Lw/2fm9q9uKCtP3+3d/n4fLTSX78U28vjn/63pPf6/feeV0svvviwev9z24fOmxvo+3/A/u+XIBkGwAA</MsgBody>
            <MsgContent>NULL</MsgContent>
            <TrangThai>N</TrangThai>
            <GUID>425F3725-7A2D-4207-A8F6-BE30FB01EE27</GUID>
            <SendOrRecv>R</SendOrRecv>
            <Terminal_ID>64998C</Terminal_ID>
            <isDaXem>0</isDaXem>
            <UserName>Root</UserName>
            <PCName>SMILEOFDEVIL-PC</PCName>
            <IsCompress>1</IsCompress>
          </Data>
        </DMSG_OUT_REP>
        <DMSG_OUT_REP>
          <Data>
            <ID>23783</ID>
            <ServiceCode>
            </ServiceCode>
            <MsgOutCode>VAD2AG0</MsgOutCode>
            <MsgOutName>Quyết định thông quan hàng hóa nhập khẩu</MsgOutName>
            <MsgDate>2021-01-07</MsgDate>
            <LoaiChungTu>10</LoaiChungTu>
            <ChungTuID>5839</ChungTuID>
            <SoChungTu>103764389520</SoChungTu>
            <MsgSubject>103764389520</MsgSubject>
            <MsgDivision>001</MsgDivision>
            <MsgTerm>E</MsgTerm>
            <MsgType>P</MsgType>
            <MsgInputID>519594001</MsgInputID>
            <MsgIndexTag>
            </MsgIndexTag>
            <MsgDes>Z</MsgDes>
            <MsgBody>GkAAAB+LCAAAAAAABADtvQdgHEmWJSYvbcp7f0r1StfgdKEIgGATJNiQQBDswYjN5pLsHWlHIymrKoHKZVZlXWYWQMztnbz33nvvvffee++997o7nU4n99//P1xmZAFs9s5K2smeIYCqyB8/fnwfPyLezIsmpf9ly/T13S/OvjhNm+Jimc/SRd402UX+Gye/cbLNz4OHT/f3npw8PDnZu3dw8unu6fGT3Yc7B8f3DvbuPXt4fPIbJyfVss2X7fab61X+KH2Tv2vvrsqsWB6m03lWN3n72UdfvXm2ffARgKbpyxTPTx4/3Tv+fGdvZ293Z3fnwe7u/m6afvfe/sO91D2f7j98eHDiffC1nt2dew8+3b938PD+3s6NjSPPS0FjZ+fe/oP79z/duf/Q/3bn4NO9hw/39x/uDr1PbXZ2T1/Sz/u7D+8/3Ke/hpt+g89PdboJ/tzZvbe7u/cbJz5xaHYwQe7BX+b/waf3aNqPd3f5BQKy/xsnD3d2HxIrHL/4/Nsvf6+fPDv7jZMdgrdzf2cXU8z97OzvOUDmt+ATemF35+Dhw4cPdg/4k5N/9G978Xn65vdJ37z49rfT3/ur//jv+cvfpC++/R//PX/9y/T3oh9/9Vfp73X2Rfr67MW3fQx/Xj6/cbL1ycH+nf17v3Hy+j/+e//k9N6Tu3sHu+nLOf54Of8n/qZ/4i9eXqRfZMWI//qP/94/n/78vYpF+rz4R/+a5Sj9iTWRdZn+Y38Stadv/rE/KRul3/5H/6L0xX/89/7ZxfjG7v+/+nR4zn7aaRS+9KNn09Mj3hfHr36v0zfpVy/OvnyRnnw5Hj1/8/T9OcoD+xsnB89GL74c76ZPvjp7/vSMlESs/bfPtt+cnnw7fX1ydvri5DT9hfjrxZfPv/z890lf/8RXx69OqRHA7D88GKXfOSPt9eL4Rfrqy+OnHUgvqIsnX47Sk2+fvTiO9MWNTl58U3yicL4OOPvq7qe7e3s7337znd9nb2d39/7uwYNnA203Pz83jT6F+Th5w3/u7R3sjHfwwe/1+Rf4gOzJzr2T09e792lmjr9Iv318lj6FDfjJrxTGT754Sn/+xon51LSKdnjygibXzHGsideWFMVD/fXk+OVp+uz5l69OX6dk5B58N9Z+Z58t4M6txv5De0I73P//MZn1ndevCfMHt4Iif5Ebtydj/b1O9CMC9OxLou1Xr5/2KLC706HL3v17BwfkYwUfcivMPj79jY2HEifnD/+7T70vFLmhmebPh+AcM8sGxLi382B/B7R4OvCm+cQQZWMHA5/+PHhR9ODezo//QnLl36TtPFvO07b6R//iJQUrd9/EXvrR86PnR0/nIQ31Gydv5hQl/IPp528+7wkOy59R4fTHrpHZoSf4En/8/+SFgAr+t2IESbHfuz9mcxa83/+bWgsRyTqk94Skp28o9H6wt7v/6f2HBwfkXXRfi0Div5ClqbNpm76oxhT9p1u79+/uPLwLzXjHb/mjZ9iUwAsJ2Xojc/ysPj93Pf/ouf3zI0750XO750ec8qPnds+POOVHz+2eH3HKj57bPT/ilJ9fz9cf7Y845UfP7Z4fccqPnts9P+KUHz23e37EKT96bvdQxvvkTXpykn77J9KT3yud/sd/z1+6vEi//TL9vX4yPTu78fX3fLD4zQv9lB7e3d3f3fu084kudff5N/7JzwKP/ca3Xsr4ed6y+9sP4UusKjzc2X24u7O70230GydP/uO/909dpsuLf/QvWaTT+T/6lyzTy3/0L0oXWdNkF7l8MkoX1Swv02dP9nZ2Rum8+o//nr+4Tf+xP/k//nv/bOL6yX/89/zN9OMf+5OL//jv/SOXKS2H/+Td+zvf/sHde/d3vjtKl/N/9C9dpnN8uU6P23m+zPjDvyhtIDXpO1rz+8vbR+kXx69+r9M36Vcvzr58kZ58OR49f/OUOv6P/94/t0h3d3Z+dzOeHz3/33g8kfgU65EvT05VUvz/xZqED829aDf8/un4ga50hm3Nmqg0jEtj+Kn85X22v3ePVOt4776BTeuim7muI/e9XgmZkxf0/2+fvTjG1094ea/zKJAIcvpRfDC3fW5YVP/JJ6QY9HfzaUhLr7H8uztElD6Eb2gEN38y8GWk4Q1M0H0GO//RmLrPj8b0/90x/cbJNj8PHj7d33ty8vDkZO/ewcmnu6fHT3Yf7hwc3zvYu/fs4fEJKbNq2ebLdvvN9Sp/lGarVVlMs7aolnffba/eTpsH201xsczadZ0fpstskX/2UbMoFvl49aD5yHu9zpbNeV5vny6n1axYXjxKJ1mTf7rvmjwtmlXVFIBNHbVtNp0v6PPD9Lwo8z7k3zj54uzs7Kvj3+c7v1f1U2fzy+mL45+YnlT02U+8OTk5ebpzcvwTp+9OfnD8nScXX9VPL744+fziq+MvjpvPT17/os9fn03u/cbJ0584/fZxdnLyZPL26uLiu7sE8XSZHT89vjg9Ob744uqT+1dXT3/C7+H0+ZOfOL76yZ8+ff7F8dvPyWbsfnX6ZP7FyU++3X/37TfHkycXL37yyXH1xbPT78wnxZOnk+sn93/q9/7q4if25qvJ4uJi+vl894vXF1ffufh9nv7kT/wE2bWnTx6i1bvZd5+tzz5/Uc2+e3959u1X9POLi+neQfjmk/3f++mb0/tfPH377sVPH//gxZuf+AHR4VlFn57t8KdP5VP67Gr2RrD0cTz96eOfEByJIF/99NPq5MmXv3GyP1n/VPbm9Ce/ePKFtL66+uInPvn809W9ry5e7S3n61/0k/e/ePX26tkVY/17PX3y5ITe+X3Onr15enH69uI3Tn5i56ef/vRX98++eH189W0d29Mns6+o1Vdv3k4vCNqD1ekXF6+//PzT6u3bi69+8iefvPnpk5Pj12dM4d848Wj8hGj89OLi9OXxU2rxE9UJ/f7k+Pf66k159/UPmk/f/uSrncm39+ZF/vTV808nu3u7y9/72ew3TuZPm4P9q4u3d5/c/31+0f7Tez/x5f1l++2n9ew7z19+/vZ0b3mS//SrJ7vFL/r277O3f2+/ePr2q+Xs5ZPdy4f3v5g+/MnqN05+0XenT5+dr67fHNw9/+r3nn+nWf/g8uyrn6iP63z/2/eLaf5892QxufrO/PTdp3frH3x+un5wMLn66cnr3/vu/mui8W+cnP/0+nUzO79arg6ady+eXzT7D6fPXn/103efL3ev756/+ulnef6d81+0f/l73f3yi2b91fHOm+Py4f79t1+c/uT+05/+fcjcvmpfnu5/ev/koP3OcvlVtZg8f3j94JOferH8wZvq7fIgf7rznYOrJyc/dfJ7f/75T+7/1Lz4Rc3L2f5XO989/smTT7/6Ns3m/PrZ3SdPXmf3Pv/OvPz89N2zu99989On95fV7m715dlPvFh/URX3ftHxveri5fG3P3n5ndN3L5/tfXFyfHV6fJx9SUJ/vGhIHr6zVO6ZnV79xMkXx/Q9zdTvc/ZTZ8e/z2T/J2hOnhz/BMnKdy8gVWj39OonTo+vzk5/4+Tg6fEKfPbt11+dnv308cWTi4v6ycXpsyc/MaU3fp+z3+vq96FZ/urbx1c/8flJQW//BLHlT0+/Or44u/oO84PXz4snTy6++6z8yR/81O99dvHVXrkkybr8KZKu7PNynZ08ucq+/dXVt3+CuO7VzpdPnvw+p8+Ov/3uN06+nOxef3Hw1b3iJ7/8pMnvfnX/05+e3dsrdr44+/wnBbcvTi9+n52ri9/nFx0/O/7q3U+82N+5rL98efWiXb/76guSi5fz5/d+n4PfZ1p995O3kzdP6i9+ork6+Qnm7s9Pr74Dqs6+eMJjPz25uPrqJxYkw6cvLs++XZaz109Iuj0M3718c/xAZO+LL15wq2e7v8939y9+n7357mQxvZiRhP8+109+QNrgp7Nv/+T9n6LvfuPkp779k+ufug7GevF7PfvO5eTeq6c/8XpB8vETV19cBPNy+uTkq++e7c13Zt8+pszB8+uHP/37vL6/nNz7fdazxf7l9PN29fzek93fp3j409PF1eXvc+94/fvc+07zxdOzz0++e/L56+PPP//k9OwJzU35rHhBcjH79qurL4uDy99n73T9U3sP954vf2pNEOrs9cOr2XfPLvH2870XV88XL64nT5/8NFP31cHp7/30SfbFyYJG8Z1Pj8s5wXo/SMdtdbK++L1+n99nSZT89qud6dPqUjC/f7sRfU7cdQLu+uoZueNXxLHPLkh7HxceP14d/z6/z3ct9D2CgLd9/H5wfIX2BMG8Uf0+b90bL+bPF7PLWXF/b1I8vMr23l5Ov/2TBX1eTpc/YXDZ+eJ4h+yFsT1keZ6cXH11fLxPdP6JJ08+eX2//onTn354Ob8o7/70k+yTL+8vPv29n71azH7yB9fr716cvHn33WfN5SXpyZ88/vLuTz989xNnL7/87ptP5rPfZ3Gy+sG3X14tHv7en3739/nBvfb5zne+M6sWZ+en737ySZm3O7tfHMy++1N75ZtXD5snhMPxd04+/32+mn5y8erZ/W+3ez+9OPi91+uLh8vPL758d/7q29fr3/vZm+9cnEy+8+zV7Nuffj7PTn+f6ge7zz75vd/8XvdP5tekJ79a7r959/kPvlsvXp2e3t1dX36Sre593uw9/8knP3hOBu3h5z84q+vTtz/1ung62/m9H2az3+vTlxfFp+fPL3+fb1+8pdl8cl39Xnu/6N5P7y+Kg8UPfp9ftP6yvtq/+Oqn5os35duzL9en3304Of/0u0+/fPmD79y73KmeT7988hPPjq+evaw/qSYUV3363Z0nu7s/8Xv91PTLV59/+4u3T6/eXO3/Xg8n737ydPf6/Pc+//J4/fnip15dtD/93Xdf/D5nJ7/3D8iWlA28gqvf+82T75LdfE9p9mX593p6vAA/iDR/e2ejNPtvnhz/4OmD5VPxSsj6q19SnX379/niyYX1TYg/vnP8A/I2Lt7+ovnb4vOHVztPiH+vvh34O2+fYRQHsP7vvnh6evUl/f+Ln367+4Ks/9lV0PL0i1ekF0/uX50/P/7i27/XD36f7N7bdX7/92l/4+TzbPXl3bsvvvPFt98G/T/9wTOSoOrq5Eq1y3e/evrk+PQXsQ/FeuJZSTqCOOrZTx8TpuXF/O3Fk5/6iS9Oj3/i7OoEWt70fzW9ehr8fUb+1ckxZOLk5BeRXEifZIMuntGn08+fvG6+pFbfNi3c96cVf+bJEUk3he5PzkiSvj2d7q4Wn97b+6ny4tnpL1ovXnz+6sXO3v2f/M7+yfFB/Xt/uXf1Uz8x/+QHq8ns9U9+99MX7fHDy9XvtT74yWf5b5y82Hnw3fmcDOzL3/vbd3fuzYofNBfPp79o8ul3prOD2U/9oP29f697V1+sV3svv7M8/kFbf/KT7+rzbzff2f/JdfFu75i4+mry+dUv+vT3/qnmJ9791Nt8ef70q3t3s9/7+Rc/+PLV3d/77ndff/lmupz/Xq9/UTM9+PLeT7/76efv9vaun51OiHnXD+tzwqH+9u/zydvl8U98/nu9+sGD7/z0VfbVzpNP7+7sVj/xdvcHDx6u3hw/2fvy872d+pPp/R9896fznbP7ZXHS/F5nv9fJLzo4viCftng4+fbb7/7en//0m4Kc2G+fffqw/X2ePv3BNc1K/eLbr6eTn/y9vvP57/P21ZPXx7/ou7/PTz8pzp/9Xp88Ozv5Rd/9RdnxvXekq3+vyeonvzh58nu9ONg9flv/xO/98O6Di5e/6Mt6Pfnis3joEAsdtrfR9v8BVkcMzBpAAAA=</MsgBody>
            <MsgContent>NULL</MsgContent>
            <TrangThai>N</TrangThai>
            <GUID>27345CDC-48C5-4021-90EE-6B2BDB53C60F</GUID>
            <SendOrRecv>R</SendOrRecv>
            <Terminal_ID>64998C</Terminal_ID>
            <isDaXem>0</isDaXem>
            <UserName>Root</UserName>
            <PCName>SMILEOFDEVIL-PC</PCName>
            <IsCompress>1</IsCompress>
          </Data>
        </DMSG_OUT_REP>
      </DMSG_OUT_REPs>
      <DHangMDDKs>
        <DHangMDDK>
          <Data>
            <_DHangMDDKID>59886</_DHangMDDKID>
            <_DToKhaiMDID>5839</_DToKhaiMDID>
            <SOTK>103764389520</SOTK>
            <MA_LH>A11</MA_LH>
            <MA_HQ>03CE</MA_HQ>
            <NAMDK>2021</NAMDK>
            <MA_NPL_SP>
            </MA_NPL_SP>
            <STTHANG>1</STTHANG>
            <MA_HANGKB>90191010</MA_HANGKB>
            <MA_HANG>NULL</MA_HANG>
            <MA_PHU>1</MA_PHU>
            <TEN_HANG>Bồn ngâm chân và massage chân, model FB200, hoạt động bằng điện 220V/50Hz/350W, nhãn hiệu Athena, nhà sản xuất: MARKET UNION CO.,LTD, mới 100%</TEN_HANG>
            <DINHMUC>NULL</DINHMUC>
            <NUOC_XX>CN</NUOC_XX>
            <TEN_NUOC_XX>CHINA</TEN_NUOC_XX>
            <MA_DVT>PCE</MA_DVT>
            <LUONG>600.00000000</LUONG>
            <DGIA_KB>16.7</DGIA_KB>
            <DGIA_TT>423141.25</DGIA_TT>
            <MA_DG>NULL</MA_DG>
            <TRIGIA_KB>10020</TRIGIA_KB>
            <TRIGIA_TT>253884750</TRIGIA_TT>
            <TGKB_VND>253884750</TGKB_VND>
            <LOAITSXNK>NULL</LOAITSXNK>
            <TS_XNK>0.00000</TS_XNK>
            <TS_TTDB>NULL</TS_TTDB>
            <TS_VAT>10.00</TS_VAT>
            <MA_NT_THUE_XNK>NULL</MA_NT_THUE_XNK>
            <THUE_XNK>0</THUE_XNK>
            <THUE_TTDB>NULL</THUE_TTDB>
            <THUE_VAT>25388475</THUE_VAT>
            <PHU_THU>NULL</PHU_THU>
            <MIENTHUE>NULL</MIENTHUE>
            <TL_QUYDOI>NULL</TL_QUYDOI>
            <MA_THKE>NULL</MA_THKE>
            <CHOXULY>NULL</CHOXULY>
            <TYLE_THUKHAC>NULL</TYLE_THUKHAC>
            <TRIGIA_THUKHAC>NULL</TRIGIA_THUKHAC>
            <Tempt>NULL</Tempt>
            <IsNoCO>NULL</IsNoCO>
            <Ma_Loai_CO>NULL</Ma_Loai_CO>
            <MaHangSX>NULL</MaHangSX>
            <TenHangSX>NULL</TenHangSX>
            <MaHSMoRong>NULL</MaHSMoRong>
            <NhanHieu>NULL</NhanHieu>
            <QuyCach_PC>NULL</QuyCach_PC>
            <ThanhPhan>NULL</ThanhPhan>
            <modelNumber>NULL</modelNumber>
            <DLoaiHangID>NULL</DLoaiHangID>
            <TEN_HANG_CHI_TIET>NULL</TEN_HANG_CHI_TIET>
            <Ma_HTS>NULL</Ma_HTS>
            <DVT_HTS>NULL</DVT_HTS>
            <LUONG_HTS>NULL</LUONG_HTS>
            <DONGIA_HTS>NULL</DONGIA_HTS>
            <TEN_HANG_E>NULL</TEN_HANG_E>
            <GHI_CHU>NULL</GHI_CHU>
            <LUONG_Y>NULL</LUONG_Y>
            <KHO_Y>NULL</KHO_Y>
            <TRI_GIA_Y>NULL</TRI_GIA_Y>
            <LOAI_HANG>1</LOAI_HANG>
            <TS_XNK_MA_BT>B01</TS_XNK_MA_BT>
            <TS_XNK_TD>NULL</TS_XNK_TD>
            <TS_TTDB_MA_BT>NULL</TS_TTDB_MA_BT>
            <TS_TTDB_TD>NULL</TS_TTDB_TD>
            <TS_VAT_MA_BT>NULL</TS_VAT_MA_BT>
            <TS_VAT_TD>NULL</TS_VAT_TD>
            <TS_MT_MA_BT>NULL</TS_MT_MA_BT>
            <TS_MT>NULL</TS_MT>
            <TS_MT_TD>NULL</TS_MT_TD>
            <THUE_MT>NULL</THUE_MT>
            <MIENTHUE_SOVB>NULL</MIENTHUE_SOVB>
            <MIENTHUE_TS>NULL</MIENTHUE_TS>
            <MIENTHUE_TS_GIAM>NULL</MIENTHUE_TS_GIAM>
            <MIENTHUE_SO_DK>NULL</MIENTHUE_SO_DK>
            <MIENTHUE_SO_DONG>NULL</MIENTHUE_SO_DONG>
            <MIENTHUE_MA>NULL</MIENTHUE_MA>
            <MIENTHUE_THUE_GIAM>NULL</MIENTHUE_THUE_GIAM>
            <MIENTHUE_MA_NT_THUE_GIAM>NULL</MIENTHUE_MA_NT_THUE_GIAM>
            <MA_TINH_TRANG>NULL</MA_TINH_TRANG>
            <IS_HANG_DONG_BO>NULL</IS_HANG_DONG_BO>
            <CHE_DO_UU_DAI>NULL</CHE_DO_UU_DAI>
            <TS_TV>NULL</TS_TV>
            <THUE_TV>NULL</THUE_TV>
            <TS_TV_MA_BT>NULL</TS_TV_MA_BT>
            <TS_TV_TD>NULL</TS_TV_TD>
            <QD_AP_HS_MA_HQ>NULL</QD_AP_HS_MA_HQ>
            <QD_AP_HS_NGAY_QD>NULL</QD_AP_HS_NGAY_QD>
            <QD_AP_HS_SO_QD>NULL</QD_AP_HS_SO_QD>
            <QD_AP_GIA_MA_HQ>NULL</QD_AP_GIA_MA_HQ>
            <QD_AP_GIA_NGAY_QD>NULL</QD_AP_GIA_NGAY_QD>
            <QD_AP_GIA_SO_QD>NULL</QD_AP_GIA_SO_QD>
            <MA_DVT_TS_XNK_TD>NULL</MA_DVT_TS_XNK_TD>
            <MA_NT_TS_XNK_TD>NULL</MA_NT_TS_XNK_TD>
            <MA_NGOAI_HAN_NGHACH>NULL</MA_NGOAI_HAN_NGHACH>
            <MA_AP_DUNG_TS_TD>NULL</MA_AP_DUNG_TS_TD>
            <LUONG2>600.00000</LUONG2>
            <MA_DVT2>PCE</MA_DVT2>
            <TRIGIA_HDTM>10020</TRIGIA_HDTM>
            <DGIA_HDTM>16.7</DGIA_HDTM>
            <MA_NT_DGIA_HDTM>USD</MA_NT_DGIA_HDTM>
            <DVT_DGIA_HDTM>PCE</DVT_DGIA_HDTM>
            <MA_NT_TRIGIA_TT>NULL</MA_NT_TRIGIA_TT>
            <SO_MUC_KHAI_DC>NULL</SO_MUC_KHAI_DC>
            <SO_MUC_KHAI_DC2>NULL</SO_MUC_KHAI_DC2>
            <SO_MUC_KHAI_DC3>NULL</SO_MUC_KHAI_DC3>
            <SO_MUC_KHAI_DC4>NULL</SO_MUC_KHAI_DC4>
            <SO_MUC_KHAI_DC5>NULL</SO_MUC_KHAI_DC5>
            <STTHANG_TN_TX>NULL</STTHANG_TN_TX>
            <HET_HAN_TN_TX>NULL</HET_HAN_TN_TX>
            <THUEKHAC_MA_AP_DUNG>VB901</THUEKHAC_MA_AP_DUNG>
            <THUEKHAC_MA_MIEN_GIAM>NULL</THUEKHAC_MA_MIEN_GIAM>
            <THUEKHAC_THUE_GIAM>NULL</THUEKHAC_THUE_GIAM>
            <THUEKHAC_MA_AP_DUNG2>NULL</THUEKHAC_MA_AP_DUNG2>
            <THUEKHAC_MA_MIEN_GIAM2>NULL</THUEKHAC_MA_MIEN_GIAM2>
            <THUEKHAC_THUE_GIAM2>NULL</THUEKHAC_THUE_GIAM2>
            <THUEKHAC_MA_AP_DUNG3>NULL</THUEKHAC_MA_AP_DUNG3>
            <THUEKHAC_MA_MIEN_GIAM3>NULL</THUEKHAC_MA_MIEN_GIAM3>
            <THUEKHAC_THUE_GIAM3>NULL</THUEKHAC_THUE_GIAM3>
            <THUEKHAC_MA_AP_DUNG4>NULL</THUEKHAC_MA_AP_DUNG4>
            <THUEKHAC_MA_MIEN_GIAM4>NULL</THUEKHAC_MA_MIEN_GIAM4>
            <THUEKHAC_THUE_GIAM4>NULL</THUEKHAC_THUE_GIAM4>
            <THUEKHAC_MA_AP_DUNG5>NULL</THUEKHAC_MA_AP_DUNG5>
            <THUEKHAC_MA_MIEN_GIAM5>NULL</THUEKHAC_MA_MIEN_GIAM5>
            <THUEKHAC_THUE_GIAM5>NULL</THUEKHAC_THUE_GIAM5>
            <MA_VB_KHAC>NULL</MA_VB_KHAC>
            <MA_VB_KHAC2>NULL</MA_VB_KHAC2>
            <MA_VB_KHAC3>NULL</MA_VB_KHAC3>
            <MA_VB_KHAC4>NULL</MA_VB_KHAC4>
            <MA_VB_KHAC5>NULL</MA_VB_KHAC5>
            <GUID>F9419202-C94E-4A4F-9D70-F8D7F73CD6B5</GUID>
            <MA_PL_XAC_NHAN_GIA>NULL</MA_PL_XAC_NHAN_GIA>
            <MA_NT_TRIGIA_TT_S>NULL</MA_NT_TRIGIA_TT_S>
            <TRIGIA_TT_S>253884750</TRIGIA_TT_S>
            <LUONG_TT>NULL</LUONG_TT>
            <MA_DVT_CHUAN>NULL</MA_DVT_CHUAN>
            <MA_NT_DGIA_TT>NULL</MA_NT_DGIA_TT>
            <DVT_DGIA_TT>PCE</DVT_DGIA_TT>
            <MA_PL_TS_TNK>A</MA_PL_TS_TNK>
            <TEN_TS_TNK>0%</TEN_TS_TNK>
            <MA_PL_NHAP_TNK>NULL</MA_PL_NHAP_TNK>
            <MA_PL_NHAP_TRGIA_TT>NULL</MA_PL_NHAP_TRGIA_TT>
            <MA_PL_NHAP_GIA_TT>NULL</MA_PL_NHAP_GIA_TT>
            <DK_MIEN_GIAM_THUE>NULL</DK_MIEN_GIAM_THUE>
            <THUEKHAC_TEN_KHOAN_MUC>Thuế GTGT</THUEKHAC_TEN_KHOAN_MUC>
            <THUEKHAC_TRGIA_TT>253884750</THUEKHAC_TRGIA_TT>
            <THUEKHAC_LUONG_TT>NULL</THUEKHAC_LUONG_TT>
            <THUEKHAC_MA_DVT_CHUAN>NULL</THUEKHAC_MA_DVT_CHUAN>
            <THUEKHAC_TEN_TS>10%</THUEKHAC_TEN_TS>
            <THUEKHAC_SO_TIEN>25388475</THUEKHAC_SO_TIEN>
            <THUEKHAC_DK_MIEN_GIAM_THUE>NULL</THUEKHAC_DK_MIEN_GIAM_THUE>
            <THUEKHAC_TEN_KHOAN_MUC2>NULL</THUEKHAC_TEN_KHOAN_MUC2>
            <THUEKHAC_TRGIA_TT2>NULL</THUEKHAC_TRGIA_TT2>
            <THUEKHAC_LUONG_TT2>NULL</THUEKHAC_LUONG_TT2>
            <THUEKHAC_MA_DVT_CHUAN2>NULL</THUEKHAC_MA_DVT_CHUAN2>
            <THUEKHAC_TEN_TS2>NULL</THUEKHAC_TEN_TS2>
            <THUEKHAC_SO_TIEN2>NULL</THUEKHAC_SO_TIEN2>
            <THUEKHAC_DK_MIEN_GIAM_THUE2>NULL</THUEKHAC_DK_MIEN_GIAM_THUE2>
            <THUEKHAC_TEN_KHOAN_MUC3>NULL</THUEKHAC_TEN_KHOAN_MUC3>
            <THUEKHAC_TRGIA_TT3>NULL</THUEKHAC_TRGIA_TT3>
            <THUEKHAC_LUONG_TT3>NULL</THUEKHAC_LUONG_TT3>
            <THUEKHAC_MA_DVT_CHUAN3>NULL</THUEKHAC_MA_DVT_CHUAN3>
            <THUEKHAC_TEN_TS3>NULL</THUEKHAC_TEN_TS3>
            <THUEKHAC_SO_TIEN3>NULL</THUEKHAC_SO_TIEN3>
            <THUEKHAC_DK_MIEN_GIAM_THUE3>NULL</THUEKHAC_DK_MIEN_GIAM_THUE3>
            <THUEKHAC_TEN_KHOAN_MUC4>NULL</THUEKHAC_TEN_KHOAN_MUC4>
            <THUEKHAC_TRGIA_TT4>NULL</THUEKHAC_TRGIA_TT4>
            <THUEKHAC_LUONG_TT4>NULL</THUEKHAC_LUONG_TT4>
            <THUEKHAC_MA_DVT_CHUAN4>NULL</THUEKHAC_MA_DVT_CHUAN4>
            <THUEKHAC_TEN_TS4>NULL</THUEKHAC_TEN_TS4>
            <THUEKHAC_SO_TIEN4>NULL</THUEKHAC_SO_TIEN4>
            <THUEKHAC_DK_MIEN_GIAM_THUE4>NULL</THUEKHAC_DK_MIEN_GIAM_THUE4>
            <THUEKHAC_TEN_KHOAN_MUC5>NULL</THUEKHAC_TEN_KHOAN_MUC5>
            <THUEKHAC_TRGIA_TT5>NULL</THUEKHAC_TRGIA_TT5>
            <THUEKHAC_LUONG_TT5>NULL</THUEKHAC_LUONG_TT5>
            <THUEKHAC_MA_DVT_CHUAN5>NULL</THUEKHAC_MA_DVT_CHUAN5>
            <THUEKHAC_TEN_TS5>NULL</THUEKHAC_TEN_TS5>
            <THUEKHAC_SO_TIEN5>NULL</THUEKHAC_SO_TIEN5>
            <THUEKHAC_DK_MIEN_GIAM_THUE5>NULL</THUEKHAC_DK_MIEN_GIAM_THUE5>
            <LEPHI_DON_GIA>NULL</LEPHI_DON_GIA>
            <LEPHI_SO_LUONG>NULL</LEPHI_SO_LUONG>
            <LEPHI_MA_DVT_LUONG>NULL</LEPHI_MA_DVT_LUONG>
            <LEPHI_SO_TIEN>NULL</LEPHI_SO_TIEN>
            <BHIEM_DON_GIA>NULL</BHIEM_DON_GIA>
            <BHIEM_SO_LUONG>NULL</BHIEM_SO_LUONG>
            <BHIEM_MA_DVT_LUONG>NULL</BHIEM_MA_DVT_LUONG>
            <BHIEM_SO_TIEN>NULL</BHIEM_SO_TIEN>
            <MA_HANG_QL_RIENG>NULL</MA_HANG_QL_RIENG>
            <TRIGIA_TT_M>NULL</TRIGIA_TT_M>
            <TS_PB>NULL</TS_PB>
            <THUE_PB>NULL</THUE_PB>
            <TS_PB_MA_BT>NULL</TS_PB_MA_BT>
            <TS_PB_TD>NULL</TS_PB_TD>
            <SO_SIZE>NULL</SO_SIZE>
            <SO_PO>NULL</SO_PO>
            <SO_CO>NULL</SO_CO>
            <DSCH810DETID>NULL</DSCH810DETID>
            <ISUSED>0</ISUSED>
            <IS_HETTON_TNTX>NULL</IS_HETTON_TNTX>
            <MA_LENHSX>NULL</MA_LENHSX>
          </Data>
          <TTKTG_PP2s>
          </TTKTG_PP2s>
          <TTKTG_PP3s>
          </TTKTG_PP3s>
          <TTKTG_PP4s>
          </TTKTG_PP4s>
        </DHangMDDK>
      </DHangMDDKs>
      <DHangMDKHs>
      </DHangMDKHs>
      <DHangMDTHs>
      </DHangMDTHs>
      <DDieuChinhs>
      </DDieuChinhs>
      <DHangMDDCs>
      </DHangMDDCs>
      <DHangMDDC_CTs>
      </DHangMDDC_CTs>
      <DVan_Dons>
      </DVan_Dons>
      <TTKTG_PP1s>
      </TTKTG_PP1s>
      <DTBTs>
        <DTBT>
          <Data>
            <DTBTID>1796</DTBTID>
            <_DToKhaiMDID>5839</_DToKhaiMDID>
            <SOTK>103764389520</SOTK>
            <NGAY_DK>2021-01-05</NGAY_DK>
            <MA_LH>A11</MA_LH>
            <MA_CUC_HQ>NULL</MA_CUC_HQ>
            <TEN_CUC_HQ>Cục Hải quan TP Hải Phòng</TEN_CUC_HQ>
            <MA_HQ>NULL</MA_HQ>
            <TEN_HQ>CC HQ CK cảng HP KV II</TEN_HQ>
            <Loai_TBT>VAF801</Loai_TBT>
            <SO_TBT>202101149285</SO_TBT>
            <Ngay_TBT>2021-01-07</Ngay_TBT>
            <Ngay_HH_TBT>NULL</Ngay_HH_TBT>
            <Tong_TH>NULL</Tong_TH>
            <TaiKhoan>7111</TaiKhoan>
            <Ten_KhoBac>Q.LÊ CHÂN</Ten_KhoBac>
            <MA_DV>0108999718</MA_DV>
            <TEN_DV>CôNG TY TNHH XUấT NHậP KHẩU KIM SINH</TEN_DV>
            <MA_BC_DV>(+84)43</MA_BC_DV>
            <DIA_CHI_DV>Số 3B/281 Phố Phương Mai, Phường Kim Liên, Quận Đống Đa, Hà Nội.</DIA_CHI_DV>
            <SO_DT_DV>0108999718</SO_DT_DV>
            <BAO_LANH_TEN_NH>NULL</BAO_LANH_TEN_NH>
            <BAO_LANH_MA_NH>NULL</BAO_LANH_MA_NH>
            <BAO_LANH_MA_A>NULL</BAO_LANH_MA_A>
            <BAO_LANH_KY_HIEU>NULL</BAO_LANH_KY_HIEU>
            <BAO_LANH_SO_CT>NULL</BAO_LANH_SO_CT>
            <BAO_LANH_TEN_LOAI>NULL</BAO_LANH_TEN_LOAI>
            <TRA_THAY_TEN_NH>NULL</TRA_THAY_TEN_NH>
            <TRA_THAY_MA_NH>NULL</TRA_THAY_MA_NH>
            <TRA_THAY_MA_A>NULL</TRA_THAY_MA_A>
            <TRA_THAY_KY_HIEU>NULL</TRA_THAY_KY_HIEU>
            <TRA_THAY_SO_CT>NULL</TRA_THAY_SO_CT>
            <TEN_SAC_THUE>Thuế GTGT</TEN_SAC_THUE>
            <TIEU_MUC>1702</TIEU_MUC>
            <TIEN_THUE>25388475.00000</TIEN_THUE>
            <TIEN_THUE_MIEN>0.00000</TIEN_THUE_MIEN>
            <TIEN_THUE_GIAM>0.00000</TIEN_THUE_GIAM>
            <TIEN_THUE_NOP>25388475.00000</TIEN_THUE_NOP>
            <TIEN_THUE_AN_DINH>NULL</TIEN_THUE_AN_DINH>
            <TIEN_THUE_CHENH>NULL</TIEN_THUE_CHENH>
            <TEN_SAC_THUE2>NULL</TEN_SAC_THUE2>
            <TIEU_MUC2>NULL</TIEU_MUC2>
            <TIEN_THUE2>NULL</TIEN_THUE2>
            <TIEN_THUE_MIEN2>NULL</TIEN_THUE_MIEN2>
            <TIEN_THUE_GIAM2>NULL</TIEN_THUE_GIAM2>
            <TIEN_THUE_NOP2>NULL</TIEN_THUE_NOP2>
            <TIEN_THUE_AN_DINH2>NULL</TIEN_THUE_AN_DINH2>
            <TIEN_THUE_CHENH2>NULL</TIEN_THUE_CHENH2>
            <TEN_SAC_THUE3>NULL</TEN_SAC_THUE3>
            <TIEU_MUC3>NULL</TIEU_MUC3>
            <TIEN_THUE3>NULL</TIEN_THUE3>
            <TIEN_THUE_MIEN3>NULL</TIEN_THUE_MIEN3>
            <TIEN_THUE_GIAM3>NULL</TIEN_THUE_GIAM3>
            <TIEN_THUE_NOP3>NULL</TIEN_THUE_NOP3>
            <TIEN_THUE_AN_DINH3>NULL</TIEN_THUE_AN_DINH3>
            <TIEN_THUE_CHENH3>NULL</TIEN_THUE_CHENH3>
            <TEN_SAC_THUE4>NULL</TEN_SAC_THUE4>
            <TIEU_MUC4>NULL</TIEU_MUC4>
            <TIEN_THUE4>NULL</TIEN_THUE4>
            <TIEN_THUE_MIEN4>NULL</TIEN_THUE_MIEN4>
            <TIEN_THUE_GIAM4>NULL</TIEN_THUE_GIAM4>
            <TIEN_THUE_NOP4>NULL</TIEN_THUE_NOP4>
            <TIEN_THUE_AN_DINH4>NULL</TIEN_THUE_AN_DINH4>
            <TIEN_THUE_CHENH4>NULL</TIEN_THUE_CHENH4>
            <TEN_SAC_THUE5>NULL</TEN_SAC_THUE5>
            <TIEU_MUC5>NULL</TIEU_MUC5>
            <TIEN_THUE5>NULL</TIEN_THUE5>
            <TIEN_THUE_MIEN5>NULL</TIEN_THUE_MIEN5>
            <TIEN_THUE_GIAM5>NULL</TIEN_THUE_GIAM5>
            <TIEN_THUE_NOP5>NULL</TIEN_THUE_NOP5>
            <TIEN_THUE_AN_DINH5>NULL</TIEN_THUE_AN_DINH5>
            <TIEN_THUE_CHENH5>NULL</TIEN_THUE_CHENH5>
            <TEN_SAC_THUE6>NULL</TEN_SAC_THUE6>
            <TIEU_MUC6>NULL</TIEU_MUC6>
            <TIEN_THUE6>NULL</TIEN_THUE6>
            <TIEN_THUE_MIEN6>NULL</TIEN_THUE_MIEN6>
            <TIEN_THUE_GIAM6>NULL</TIEN_THUE_GIAM6>
            <TIEN_THUE_NOP6>NULL</TIEN_THUE_NOP6>
            <TIEN_THUE_AN_DINH6>NULL</TIEN_THUE_AN_DINH6>
            <TIEN_THUE_CHENH6>NULL</TIEN_THUE_CHENH6>
            <TONG_TIEN_THUE>25388475.00000</TONG_TIEN_THUE>
            <TONG_TIEN_THUE_MIEN>0.00000</TONG_TIEN_THUE_MIEN>
            <TONG_TIEN_THUE_GIAM>0.00000</TONG_TIEN_THUE_GIAM>
            <TONG_TIEN_THUE_NOP>25388475.00000</TONG_TIEN_THUE_NOP>
            <TONG_TIEN_THUE_AN_DINH>NULL</TONG_TIEN_THUE_AN_DINH>
            <TONG_TIEN_THUE_CHENH>NULL</TONG_TIEN_THUE_CHENH>
            <MA_NT>VND</MA_NT>
            <TY_GIA>1.00000</TY_GIA>
            <SO_NGAY_AN_HAN>1</SO_NGAY_AN_HAN>
            <NGAY_HET_HAN_TNTX>2021-01-05</NGAY_HET_HAN_TNTX>
            <LAI_PHAT_CHAM_NOP>Nếu chậm nộp tiền thuế so với thời hạn quy định thì phải nộp tiền chậm nộp theo mức tại khoản 32 Điều 1 Luật sửa đổi, bổ sung một số điều của Luật Quản lý thuế.</LAI_PHAT_CHAM_NOP>
            <BAO_LANH_NAM_CT>NULL</BAO_LANH_NAM_CT>
            <TRA_THAY_NAM_CT>NULL</TRA_THAY_NAM_CT>
            <LOAI_TOKHAI>TOKHAI</LOAI_TOKHAI>
          </Data>
          <DTBT_CTs>
          </DTBT_CTs>
        </DTBT>
      </DTBTs>
      <DTOKHAIMD_GPs>
      </DTOKHAIMD_GPs>
      <DTOKHAIMD_COs>
      </DTOKHAIMD_COs>
      <DTOKHAIMD_DeNghiChuyenCKs>
      </DTOKHAIMD_DeNghiChuyenCKs>
      <DLogInfos>
        <DLogInfo>
          <Data>
            <ID>31184</ID>
            <ToKhaiID>5839</ToKhaiID>
            <MsgDes>Khai báo thành công.
    Đã được cấp số tờ khai: 103764389520</MsgDes>
            <MsgType>Thông tin phản hồi</MsgType>
            <LogDate>2021-01-05</LogDate>
            <LogTime>2021-01-05</LogTime>
            <Loai>TK</Loai>
          </Data>
        </DLogInfo>
        <DLogInfo>
          <Data>
            <ID>31185</ID>
            <ToKhaiID>5839</ToKhaiID>
            <MsgDes>Khai báo tờ khai thành công</MsgDes>
            <MsgType>Thông tin phản hồi IDC</MsgType>
            <LogDate>2021-01-05</LogDate>
            <LogTime>2021-01-05</LogTime>
            <Loai>TK</Loai>
          </Data>
        </DLogInfo>
        <DLogInfo>
          <Data>
            <ID>31186</ID>
            <ToKhaiID>5839</ToKhaiID>
            <MsgDes>Tờ khai đã được phân luồng. Luồng của tờ khai là:Do</MsgDes>
            <MsgType>Thông tin phản hồi</MsgType>
            <LogDate>2021-01-05</LogDate>
            <LogTime>2021-01-05</LogTime>
            <Loai>TK</Loai>
          </Data>
        </DLogInfo>
        <DLogInfo>
          <Data>
            <ID>31331</ID>
            <ToKhaiID>5839</ToKhaiID>
            <MsgDes>Thực hiện thành công.</MsgDes>
            <MsgType>Thông tin phản hồi IID</MsgType>
            <LogDate>2021-01-08</LogDate>
            <LogTime>2021-01-08</LogTime>
            <Loai>TK</Loai>
          </Data>
        </DLogInfo>
        <DLogInfo>
          <Data>
            <ID>31332</ID>
            <ToKhaiID>5839</ToKhaiID>
            <MsgDes>Tờ khai đã được chấp nhận thông quan</MsgDes>
            <MsgType>Thông tin phản hồi</MsgType>
            <LogDate>2021-01-08</LogDate>
            <LogTime>2021-01-08</LogTime>
            <Loai>TK</Loai>
          </Data>
        </DLogInfo>
      </DLogInfos>
      <DToKhaiMD_HoaDonTMs>
      </DToKhaiMD_HoaDonTMs>
      <DToKhaiMD_HopDongTMs>
      </DToKhaiMD_HopDongTMs>
    </Root>`
  );
  
  const element = document.createElement("a");
  const file = new Blob([doc], {type: 'xml'});
  element.href = URL.createObjectURL(file);
  element.download = item.name + ".xml";
  document.body.appendChild(element); // Required for this to work in FireFox
  element.click();
};

const DownloadXmlFile = ({ awb }) => {
  const hawb={
    name: awb,
    number: 122333333333
  };
  return (
    <Button
      aria-label="Print Licensee profile"
      aria-haspopup="false"
      color="primary"
      onClick={() => { downloadTxtFile(hawb); }}
    >
      Download XML file
    </Button>  
  );
};

export default DownloadXmlFile;
